---
title: "[Das Notizbuch](https://sbalci.github.io/DeutschLernen/Notizbuch.nb.html)"
output: 
  html_notebook: 
    code_folding: hide
    fig_caption: yes
    toc: yes
    toc_depth: 4
    toc_float: yes
---


# A2 {.tabset .tabset-fade .tabset-pills}

https://hueber.de/shared/uebungen/menschen/kb/a2/menu.php

https://www.hueber.de/media/36/Menschen_Loesungen_AB_A2.pdf

---

## 1

Mein Opa war auch schon Bäcker.

die Brezel | die Brezeln  

klappen  

kompliziert  

der Teig | die Teige  

das Studium  

das Einrad | die Einräder  

das Fußballbild | die Fußballbilder  

klettern  

übernachten  

das Skateboard | die Skateboards  

die Süßigkeiten  


auf Bäume klettern  
Comics lesen  
Computerspiel spielen  
draußen übernachten  
Einrad fahren  
Sachen auf dem Flohmarkt verkaufen  
mit Puppet spielen  
Geschicten erzählen  
Fußballbilder sammeln  
zeichnen  
Witze erzählen  
Süßigkeiten essen  
Skateboard fahren  

der Ausschnitt | die Ausschnitte    
der Bäcker | die Bäcker  
die Bäckerin | die Bäckerinnen  
der Cousin | die Cousins  
der Neffe | die Neffen  
die Nichte | die Nichten  
der Schwiegersohn | die Schwiegersöhne  
der Schwiegervater | die Schwiegerväter  


übergeben  


die Zigarette | die Zigaretten  

verrückt (sein)  

wachsen  

der Judenliche | die Judenlichen  
die Kindheitserinnerungen  
Familienheitserinnerungen  
die Lieblingsdisco | die Lieblingsdiscos  
die Sekunde | die Sekunden  
das Wahrheitsspiel | die Wahrheitsspiele  

aufmachen  
der Schluss  
zum Schluss  

die Abstimmung | die Abstimmungen  

das Ereignis | die Ereignisse  

die Familiengeschichte  
Familiengeschichten erzählen  
die Geschichte | die Geschichten  

streiten | haben gestritten (to fight)  
Glück haben  
rufen | haben gerufen  
hören | haben gehört  
sagen | haben gesagt  
bestehen | haben bestanden  (to pass)  
besuchen | hat besucht (to visit)  
umziehen | haben umgezogen (to move)


Meine Schwester und ich haben als Kinder viel gestritten.  

Es gab ein Unwetter, aber wir hatten Glück. Es ist nichts passiert.  

Ich habe dich gerufen, aber du hast mich leider nicht gehört.  

Jan hat mir gesagt, Alina hat ihre Prüfung bestanden.  

Letzte Woche haben wir Xaver und Michele besucht. Sie sind umgezogen.  


Kolja, habe ich dir schon von meinem Cousin Fridolin erzählt?  
Nach der Schule hat er **zuerst** eine Ausbildung als Friseur gemacht. Er war immer fleißig und hat schon mit 18 Jahren einen eigenen Friseursalon aufgemacht. Er hat viel Geld verdient und sein Geschäft ist viel gewachsen.  
Und weißt du, **was dann passiert ist**? Eines Morgens hat er allen erzählt: Ich verkaufe das Geschäft. Er hat aber nicht sofort einen Käufer gefunden.  
**Zum Schluss** hat er das Geschäft einfach geschlossen, ein paar Sachen gepackt und ist nach Alaska geflogen. Heute lebt er dort allein in den Wäldern und ist glücklich.


Also passt auf: ...

Und wisst ihr, was ... dann gemacht hat?

Wisst ihr, was dann passiert ist?

Er / Sie war schon verrückt / nett / lustig, mein / meine ...






---

## 2

Wohin mit der Kommode?  

umziehen  

blöd  

ein·richten  

renovieren  


diskutieren  

das Fernsehgerät | die Fernsehgeräte  
hängen  
das Kissen | die Kissen  
verstecken  

die Gemeinsamkeit | die Gemeinsamkeiten  

**Im Zimmer**  

die Kommode | die Kommoden  
die Wand | die Wände  
das Regal | die Regale  
die Lampe | die Lampen  
das Fernsehgerät | die Fernsehgeräte  
der Schreibtisch | die Schribetische  
der Stuhl | die Stühle  
der Tisch | die Tische  
der Schrank | die Schränke  
der Vorhang | die Vorhänge  
das Bett | die Betten  
das Kissen | die Kissen  
das Sofa | die Sofas  
die Couch | die Couchs  
der Sessel | die Sessel  
der Teppich | die Teppiche  


bis: bis hin  
das Deckenlischt | die Deckenlichter  

direkt  X indirekt  
dunkel  X hell  


die Domizil-Redaktion | die Domizil-Redaktionen  


die Geschmackssache  
das Heft | die Hefte  

der Klassiker | die Klassiker  
die Kuschel-Ecke  

das Möbelstück | die Möbelstücke  
das Regal | die Regale  

der Romantiker | die Romantiker  
die Romantikerin | die Romantikerinnen  

die Sofa-Landschaft | die Sofa-Landschaften  

gemütlich X ungemütlich  

das Urlaub-Souvenir | die Urlaub-Souvenirs  

der Spiegel | die Spiegel  

das Werkzeug | die Werkzeuge  

der Einrichtungstipp | die Einrichtungstipps  
Einrichtungstipp geben  

der Magazintext | die Magazintexte  
der Umzug | die Umzuge  

die Wechelpräposition | die Wechelpräpositionen  

das Möbelhaus

legen  
stellen  
hãngen

Ich lege die Zeitung auf die Couch.

Wir stellen das Geschirr in die Küchenschränke.

Legst du bitte den Bleistift neben das Papier?

Julia hãngt die Lampe über den Tisch.


*Im Möbelhaus*

Das ist doch ein toll*es* Bild. Das können wir *über das Sofa* hängen.
Aber bei uns hãngen doch schon so viele Bilder *über dem Sofa*.


Der Teppich ist schön und nicht mal teuer. *Den* legen wir *in das Schlafzimmer*.
Aber *vor dem Bett* liegt doch schon ein Teppich.

Da steht eine Kommode *zwischen zwei Fenstern*. Das sieht gut aus.
Ja, hier schon. Aber *in unserer Wohnung* können wir diese Kommode nicht *zwischen die Fenster stellen*. Sie ist viel zu groß.


In der neuen Wohnung.

Stell lieber nicht zu viele Möbel in das Zimmer. Sonst ...

( lieber nicht zu viele Möbel in das Zimmer stellen / sonst Raum noch kleiner werden)
( einen Spiegel an Wand hängen / dann Raum größer aussehen)
( vorsichtig sein mit dunklen Möbeln)























---

## 3

Hier finden Sie Ruhe und Erholung  

Grüzei mitenand  
Tach  

"Tach" und "Grüzei mitenand" bedeutet "Guten Tag".

die Region | die Regionen  
das Dorf | die Dörfer  
der Froch | die Fröche  
der Hügel | die Hügel (hill)  
die Katze | die Katzen  
die Pflanze | die Pflanzen  

Ich mache eine Fahrt durch die Dörfer | über die Hügel.  

der Strand | die Strande  (beach)  
das Ufer | die Ufer  (river bank)  
der Vogel | die Vögel  
der Wald  
der Fisch | die Fische  
der Hund | die Hunde  

aktiv  
Ich bin sportlich aktiv  

anders gehen  

der Anfänger | die Anfänger  (beginner, amateur)  
der/die Fortgeschrittene | die Fortgeschritennen (advanced learner)  


die Anfängerin | die Anfängerinnen  
die Anstrengung | die Ansterngungen  (effort)  
die Ausrüstung | die Ausrüstungen (equipment)  
außerdem  (also, in addition)  
der Bauernhof | die Bauernhofe  (farm)  

beraten (advice)  
die Beratung | die Beratungen  (consultation)  
der Bergkräuterre | die Bergkräutertees  (çiçek çayı)  
der Bodensee  (Lake Constance)  
der Campaignplatz | die Campaignplätze  
der Einkaufsbummel  

enden  

entlang  (alongside)  

die Entspannung (relaxation)  
die Erholung (rest)  
die Erfahrung (eperience)  
der Extra-Service  
der Großstadt-Fan | die Großstadt-Fans  

hellgrün (açık yeşil)



hinunter (down)   
den Fluss hinunter (down the river)  

ideal  

das Inntal  (Valley of Inn)  

der/das Kajak | die Kajaks (kano)  
das Kite-Surfen  (windsurf)  
die Landschaftsreise | die Landschaftreisen  
die Städtreise | die Städtreisen  
die Motivation | die Motivationen  

die Naturliebhaberin | die Natürliebhaberinnen  

offen (sein)  

quacken  

das Salzhaff | die Salzhaffe / Salzhaffs (ein durch von der Ostsee)  

die Schweizer Alpen  

die Segel-Schule  
die Surf-Schule | die Surf-Schulen  
der Spreewald  (the Green Venice near Berlin)  
der Stadtbummel  (şehir turu)  

Stopp!

das Superangebot | die Superangebote  (super offer)  
die Surf-Mode  
der Top-Preis | die Top-Preise  
die Tour | die Touren  
die Velo-Tour | die Velo-Touren (bicycle tour)  
der Velovermieter  
der Wanderer | die Wanderer (hiking man)
die Wanderin | die Wanderinnen  
die Wanderung  
das Wesserwandern  
der Werbetext | die Werbetexte  (adversiting text)  

worauf (whereon)  
Worauf wartest du noch?  

die Mode | die Moden  
die Mitte | die Mitten (middle)  

in sein  
Kite-Surfen ist gerade in (Windsurf is just in)  

das Stichwort | die Stichwörter (keyword)  

der Trend | die Trends  

die Geschäftsidee | die Geschäftsideen  
der Reiseveranstalter (seyhat oragnizatörü)  
Veranstalter(in) (organizatör)  
der Rodel (kızak)  
die Schlittenfahrt | die Schlittenfahrten  (kızak kaymak)  
die Shikurs | die Shikurse  

ausdrücken  (yazdırmak)  
bewerten  (değerlendirmek)  
buchen  
touristisch  

überhaupt (eninde sonunda) X überhaupt nicht (asla)  
Mir gefãllt das Angebot überhaupt nicht  

die Vorliebe | die Vorlieben (eğilim)  
die Werbebroschüre | die Werbebroschüren  (reklam broşürü)  

50er-Jahre  
auswandern  
besitzen  (to possess)  























Das Angebot gefällt mir

Welches Angebot gefällt Ihnen am besten?

Wie finden Sie die Idee?
Warum?
Würden Sie diese Reise buchen?
Warum / Warum nicht?

ganz in Ordnung
viele Menschen haben zu viel Stress
auf keinen Fall
zu langweilig, zu wenig Menschen


*Nomen mit -ung*

wandern | die Wanderung (to hike, hiking)  
erfahren | die Erfahrung (experience)  
anstrengen | die Anstrengung (effort)  
beraten | die Beratung (advice)   
anmelden | die Anmeldung (register, apply, application)  
erholen | die Erholung (rest)  


*Was war früher anders als heute?*  
Früher habe ich am Tag 20 Zigaretten geraucht, heute lebe ich gesünder.    
Als Kind habe ich mit Puppen gespielt. Meine Tochter findet Computerspiele interessanter.  
In unserem Dorf war die Luft früher besser, heute gibt es viele Fabriken.   
Meine Großeltern haben auf einem Bauernhof gelebt, wir wohnen in der Stadt.  
In meiner Kindheit hatten wir auch kein Fernsehgerät.  
Meine Schwiegermutter hat früher mit Holz gekocht, jetzt hat sie einen Herd.  
Der Unterricht in der Schule war anders, heute diskutieren die Lehrer mehr mit den Schülern.



1. Christian kann den Schlüssel nicht finden.

2. Melanie und Max sind die neuen Nachbarn von Lena und Christian.

3. Lena und Christian haben sich Hamburg kennengelernt.

4. Sie sind nach München gezogen, weil Christian ein tolles Jobangebot bekommen hat.

5. Lena und Christian brauchen doch keinen Schlüsseldienst, weil Max den Schlüsselbund auf der Straße gefunden hat.

6. Max hilft Lena mit demTisch.


Mit Brot und Salz wünschen Nachbarn Glück im neuen Haus.

Ein zerbrochener Spiegel bedeutet sieben Jahre Pech.

Scherben bringen Glück.


*Gefühle beim Umzug*

Schreiben Sie einem Freund eine Mail und erzählen Sie ihm, welche Gefühle Sie beim Umzug hatten, und ob Sie von jemand einen Glücksbringsel bekommen haben.

Schreiben Sie mindestens 50 Wörter.

Beginnen Sie so:

Liebe…/Lieber…,

in der letzten Woche bin ich...

Redemittel:

sich auf die neue Wohnung freuen/ der Stress, dass man alles packen und bewegen muss/ ein schlechtes Gefühl, weil man einen Lebensabschnitt hinter sich lässt/ Freunde/ eine bekannte Umgebung















Michael steht um 8.15 Uhr auf.
Michael ist um 8.15 Uhr aufgestanden.

Er duscht und putzt sich die Zähne.
Er hat geduscht und sich die Zähne geputzt.

Dann kocht er Kaffee und mach Frühstück. 
Dann hat er Kaffee gekocht und Frühstück gemacht.

Michael isst Toast mit Honig , ein Ei und Müsli.
Michael hat Toast mit Honig , ein Ei und Müsli gegessen.

Er liest die Zeitung.
Er hat die Zeitung gelesen.


Um 9.30 Uhr geht Michael zur Schule , er zieht seinen Mantel an und holt das Fahrrad.
Um 9.30 Uhr ist Michael zur Schule gegangen,er hat seinen Mantel angezogen und das Fahrrad geholt.

Er fährt durch die Stadt und hält am Kiosk.
Er *ist* durch die Stadt und *hat* am Kiosk gehalten.

Dort kauft er Süßigkeiten und Kaugummi.
Dort hat er Süßigkeiten und Kaugummi gekauft.

Um 10.00 Uhr kommt Michael in der Schule an und geht in die Klasse. Alle anderen sind schon da.
Um 10 Uhr ist Michael in der Schule angekommen und ist in die Klasse gegangen.Alle anderen sind schon da gewesen.



---

## 4







Viele Grüße aus Köln

Die Oma schreibt einen Brief an ihren Mann.

Die Mutter schreibt eine Postkarte an ihren Mann..

Die Tochter schreibt eine Facebook-Nachricht an ihre Freundin.

1. Jutta freut sich am meisten auf den Ausflug mit dem Schiff.

2. Melanie hat Charlottes Kamera im Hotel abgegeben.

3. Charlotte ärgert sich: Sie hat ihre neue Kamera im Dom vergessen.


Der berühmte Dom ist wirklich sehenswert

berühmt (famous)  
sehenswert (worth seeing)  


*Nominativ*  
Mir gefällt/gefallen ...    
der berühmt*e* Dom  
das bunt*e* Fenster   
die neu*e*  Kamera  
die nett*en*  Leute  


*Akkusativ*  
Ich finde  ... toll      
*den* alt*en* Dom  
das  bunt*e*  Fenster  
die neu*e*  Kamera   
die nett*en* Leute  


*Dativ*  
mit ...               
*dem* nett*en*     Reiseführer  
*dem* bunt*en*    Fenster  
*der* neu*en*       Kamera  
*den* nett*en*      Leuten  



https://www.koelntourismus.de/

Am Samstagmorgen.../Zuerst.../Mittags.../Am Nachmittag..../Am Abend..../ Und am Sonntag..../Was denkst du?

Ich schlage vor, wir gehen in den Kölner Dom, denn das ist das Wahrzeichen von Köln.










---

## 5








die schön*en* X hässlich*en* Postkarten
der geschlossene X geöffnete Supermarkt
die langweilige X lustige Stadtführung
die lange X kurze Schifffahrt
das gute X schlechte Wetter
das alte X neue Haus
der kurze X lange Brief


Den alten Dom finde ich viel schöner als die moderne Kirche.  
In den bunten Prospekten sieht die Stadt viel schöner aus.  
Die alte Kamera ist total schwer. Warum hast du denn nicht die neue mitgenommen?  
In dem schicken Restaurant neben der Post würde ich auch gerne essen.  
Hast du das nette Cafe gesehen? Da können wir nach der Führung hingehen.  
Warum hast du denn die billigen Postkarten gekauft?  
Wie findest du denn das grüne Haus mit dem kleinen Turm da vorne?  
In der kleinen Kirche waren wir ja schon.  


Hallo ...,
viele Grüße aus dem schönen Wien.
Die Stadt ist toll. Am ersten Tag habe ich einen langen Rundgang durch das Zentrum gemacht. Der Stadtführer war ein total lustiger junger Wiener. Die alten Häuser hier finde ich besonders schön. Ich habe auch eine nette Schifffahrt auf der schönen blauen Donau gemacht. Gestern Abend war ich im berühmten Burgtheater. Die Schauspieler waren wirklich toll. Leider habe ich keine billige Unterkunft gefunden. Das Hotel liegt auch noch in einem ziemlich langweiligen Stadtviertel. Aber sonst ist es hier toll. Ich hoffe, du hast auch schöne Ferien.
Bis bald!
..








---

## 6



---

## 7



---

## 8



---

## 9



---

## 10



---

## 11



---

## 12



---

## 13



---

## 14



---

## 15



---

## 16



---

## 17



---

## 18



---

## 19



---

## 20



---

## 21



---

## 22



---

## 23



---

## 24


























---









# Wörterbuch {.tabset .tabset-fade .tabset-pills}

---

## Leo

https://www.leo.org/german-english

https://dict.leo.org/trainer/joinGroup.php?token=30XGI2UJ&lp=ende&lang=en

---

## Pons

https://en.pons.com/translate

---

## Duden

https://www.duden.de/

---

## Korrekturen

Superlativ-Komparativ

https://www.korrekturen.de

---

## Hueber

https://www.hueber.de/woerterbuch/online

http://www.hueber.de/drop-a-word-go/

---

# Bibliothek {.tabset .tabset-fade .tabset-pills}

---


## Mein Goethe

https://my.goethe.de/

---

## Onleihe

http://www2.onleihe.de/goethe-institut/frontend/welcome,51-0-0-100-0-0-1-0-0-0-0.html?lK=656e

---

## Ankara Bibliothek


https://ankara.bibliothek.goethe.de 


---


# Media {.tabset .tabset-fade .tabset-pills}

---

## N-TV

https://www.n-tv.de/mediathek/livestream/

---

## DW

- A1 SEVİYESİ

https://www.dw.com/tr/almanca-%C3%B6%C4%9Frenin/a1-seviyesi-i%C3%A7in-%C3%B6%C4%9Frenme-imk%C3%A2nlar%C4%B1/s-30095

- Placement Test

https://learngerman.dw.com/en/placementDashboard

- A1, A2, B1 | Deutsch Interaktiv

https://www.dw.com/tr/almanca-%C3%B6%C4%9Frenin/deutsch-interaktiv/s-11205

- A1, A2, B1 | Deutsch – warum nicht?

https://www.dw.com/tr/almanca-%C3%B6%C4%9Frenin/deutsch-warum-nicht/s-2609

- A1 | Mission Europe

https://www.dw.com/tr/almanca-%C3%B6%C4%9Frenin/mission-europe/s-11206

- A1 | Radio D – Bölüm 1

https://www.dw.com/tr/almanca-%C3%B6%C4%9Frenin/radio-d-1-b%C3%B6l%C3%BCm/s-11211

- A1, A2 | SES DOSYALARI EŞLİĞİNDE ALMANCA

https://www.dw.com/tr/almanca-%C3%B6%C4%9Frenin/audiotrainer/s-11213




---

## YouTube

- Die Deutschen (The Germans) S01E09 'Bismarck und das Deutsche Reich' (Ger&Eng Subs)  
https://www.youtube.com/watch?v=Tyeu2Z_p9sM


- National Geographic  
https://www.youtube.com/watch?v=4J5i3yxH1ks&list=PLfBYdQ3Qs3IrRDjHUv-ny-t8_usQfP1PB

- Easy German

https://www.youtube.com/channel/UCbxb2fqe9oNgglAoYqsYOtQ

---

# Namen {.tabset .tabset-fade .tabset-pills}

---

## Namen Nominativ  {.tabset .tabset-fade .tabset-pills}

Genus (Gender)  
*maskuline* der Tisch  
*neutral* das Bild  
*feminine* die Lampe

Registrierungscode  
Stadt Städte 
Städtenamen  
die Taxis  
Pause  
Gespräch  
ein paar Hande  
ehepaar  


Mann | Männer  
Frau | Frauen  
Visitenkarte | Visitenkarten  
Beruf | Berufe  
Buch | Bücher  
Lehrerin | Lehreninnen  
Lehrer | Lehrer  
Kursteilnehmerin | Kursteilnehmerinnen  
Kursteilnehmer | Kursteilnehmer  
Fenster | Fenster  
Tisch | Tische  


das Haus + die Frau -> die Hausfrau  

Was ist der Artikel von ... ?  
Der Artikel von Ball ist der.  



---

### der
<span style="color:blue">
der Aufzug | die Aufzüge  
der Supermarkt  
der Dom  
der Ausweis  
der Weg | die Wege
der Navigator | die Navigatoren  
der Stadtplan | die Stadtpläne
der Bahnof  
der Brücke  
der Würfel  
der Stab  
 | die Stadtmitte  
der Tisch
der Ball
</span>





---

### die
<span style="color:red">
die Disco  
die Sprachshule  
die Post
die Bank National  
die Polizei  
die Bank  
die straße | die straßen
die Ampel  
die Bushaltestelle  
die Pyramide  
die Brücke  
die Beiden  
die Nähe  
die Ferne  
die Lampe  
die Tasche  
.  
..heit  
..keit  
..ung  
.  
</span>



---

### das
<span style="color:green">
das Fahrrad  
das Scwhimmbad  
das Museum  
das Politzeiauto  
das Restaurant  
das Auto | die Autos  
das Hotel | die Hotels  
das Zentrum  
das Kino
das Café  
das Teppichmesser (Maket bıçağı)  
das Handy  
das Bild  
das Möbel  
das Bett  
das Haus | die Häuser  

</span>

---

---

## Namen Akkusativ {.tabset .tabset-fade .tabset-pills}

| **DATİV**      | **Dativ oder Akkusativ**     | **AKKUSATIV**      | 
|---             |---                           |---                 |
| aus            | **an**                       | durch              | 
| bei            | **auf**                      | für                | 
| mit            | **hinter**                   | gegen              | 
| nach           | **in**                       | ohne               | 
| seit           | **neben**                    | um                 | 
| von            | **über**                     |                    | 
| zu             | **unter**                    |                    | 
|                | **vor**                      |                    | 
|                | **zwischen**                 |                    |

**Wo---> DATİV**

z.B

der Schrank -- > in dem Schrank
die Tasche --> in der Tasche
das Regal --> in dem Regal
die Autos --> in den Autos

an dem --> am
bei dem --> beim
in dem --> im
von dem -->vom
zu dem -->zum / zu der --> zur

**Wohin?-----> Akkusativ**

der Schrank --> in den Schrank
die Tasche --> in die Tasche
das Regal --> in das Regal
die Autos --> in die Autos

an das --> ans
in das --> ins

## Namen Akkusativ {.tabset .tabset-fade .tabset-pills}


---

## Namen Dativ {.tabset .tabset-fade .tabset-pills}




die Bank -> der Bank  
die Ampel -> der Ampel  
die Brücke -> der Brücke  

an dem Bahnof
am Bahnoff  
zwischen dem Supermarkt und dem Hotel
hinter der Häusern
in dem Zentrum  
im Zentrum  
neben der Polizei  
zwischen dem Bahnoff und der Post  
vor der Bank
hinter der Brücke  
neben dem Museum
vor dem Restaurant


---

### der -> dem  {.tabset .tabset-fade .tabset-pills}

der/ein Bahnhof | vor dem einem Bahnhof


---

### das -> dem  {.tabset .tabset-fade .tabset-pills}

das ein Restaurant | vor dem einem Restaurant
das Zentrum | in dem (im) Zentrum

---

### die -> der  {.tabset .tabset-fade .tabset-pills}

die eine Ampel | vor der einer Ampel

die Stadtmitte | in der Stadtmitte

---

### die pl. -> den + n  {.tabset .tabset-fade .tabset-pills}

die Cafés/Häuser | vor den Cafés/Häusern








---

# Verben {.tabset .tabset-fade .tabset-pills}


kommen  
verbstamm (komm)  
endung (en)  

## regelmaßige Verben

haben--gehabt
machen--gemacht
sagen--gesagt
üben--geübt
antworten--geantwortet
arbeiten--gearbeitet
kochen--gekocht
lernen--gelernt

## unregelmaßige verben
  
 sprechen--gesprachen
 scgreiben--geschieben
 treffen--getroffen
 nehmen--genommen
 trinken--getrunken
 singen--gesungen
 finden--gefunden
 essen-gegessen
 sehen--gesehen
 lesen--gelesen
 backen-gebacken
 
## Regelmaßige trennbare verben

 --ge---t
aufraumen--aufgeräumt
einkaufen--eingekauf
abholen--abgeholt

## unreglmäßige trennbare verben

anrufen-angerufen
einladen--eingeladen
fernsehen--ferngesehen

## verben auf -ieren

telefonieren--telefoniert
fotografieren-fotografiert
markieren--markiert





---

## Konjugieren  

| **verb**      | **ich**     | **du**      | **er/sie/es**   | **wir**     | **ihr**     | **sie/Sie**     |
|---            |---          |---          |---              |---          |---          |---              |
| *kommen*      | komme       | kommst      | kommt           | kommen      | kommt       | kommen          | 
| *heißen*      | heiße       | heißt       | heißt           | heißen      | heißt       | heißen          | 
| *wohnen*      | wohne       | wohnst      | wohnt           | wohnen      | wohnt       | wohnen          | 
| *arbeiten*    | arbeite     | arbeitest   | arbeitet        | arbeiten    | arbeitet    | arbeiten        | 
| *leben*       | lebe        | lebst       | lebt            | leben       | lebt        | leben           | 
| *kennen*      | kenne       | kennst      | kennt           | kennen      | kennt       | kennen          | 
| *hängen*      | hänge       | hängst      | hängt           | hängen      | hängt       | hängen          | 

suchen  
zahlen  



---

## Verb mit Vokal wechsel

e -> i (2-3 singular)


| **verb**      | **ich**     | **du**      | **er/sie/es**   | **wir**     | **ihr**     | **sie/Sie**     |
|---            |---          |---          |---              |---          |---          |---              |
| *sprechen*    | spreche     | sprichst    | spricht         | sprechen    | sprecht     | sprechen        |
| *helfen*      | helfe       | hilfst      | hilft           | helfen      | helft       | helfen          |
| *tragen*      | trage       | trägst      | trägt           |             |             |                 |
| *gefallen*    | gefalle     | gefällst    | gefällt         | gefallen    | gefallt     | gefallen        |
| *werden*      | werde       | wirst       | wird            | werden      | werdet      | werden          |







---

## Modalverben

| **verb**      | **ich**   | **du**    | **er/sie/es** | **wir**   | **ihr**   | **sie/Sie**   |
|---            |---        |---        |---            |---        |---        |---            |
| *sein*        | bin       | bist      | ist           | sind      | seid      | sind          |
| *haben*       | habe      | hast      | hat           | haben     | habt      | haben         |
| *sollen*      | soll      | sollst    | soll          | sollen    | sollt     | sollen        |
| *können*      | kann      | kannst    | kann          | können    | könnt     | können        |
| *wollen*      | will      | willst    | will          | wollen    | wollt     | wollen        |
| *dürfen*      | darf      | darfst    | darf          | dürfen    | dürft     | dürfen        |
| *müssen*      | muss      | musst     | muss          | müssen    | müsst     | müssen        |


möchten

Du sollst diesen Tee trinken.  

Fabian will lieder macher werden.  
Ich möchte ... (Beruf) werden.  

Ich will ein Auto kaufen.  
Ich will durch Europa reisen.  



---

## Trenbare


| **verb**      | **ich**   | **du**    | **er/sie/es** | **wir**   | **ihr**   | **sie/Sie**   |
|---            |---        |---        |---            |---        |---        |---            |
| anfangen      | fange an  | fängst an | fängt an      | fangen an | fangt an  | fangen an     |




anfangen
anmachen X ausmachen  
anmachen X aufmachen  
einladen  
aufhören  
fernsehen  
abgieben  
umsteigen  
mitbringen  
abfahren  
aufstehen  
auskommen  





*Nicht trenbare verben:  *

be-  
ver-  
er-  
ent-  
miss-  
zer-  
emp-  
ge-  




---

## Name + Verb

Husten haben  






---

## Pz II

gewinnen | gewonnen





---

# Adjektiven {.tabset .tabset-fade .tabset-pills}






---

# Regel {.tabset .tabset-fade .tabset-pills}


dann, dannach, leider (position 1)  
aber, und (position 0)  

dann bin ich ... (dann + V in pos 2 + Subj)

aber ich bin ... (aber + sub + V in pos 2)






---

## Artikel  


das Haus + die Frau -> die Hausfrau 








---

## Doch  

Woher kommen Sie? Ich komme aus Ankara.  

Kommen Sie aus Ankara? -> (+) Ja, ich komme aus Ankara. (-) Nein, ich komme nicht aus Ankara.  
Kommen Sie nicht aus Ankara? -> (+) Doch, ich komme aus Ankara. (-) Nein, ich komme nicht aus Ankara.








---

## nicht keine

nicht: negation adjektive  
keine: negation name  

Ich bin nicht verheiratet.  
Ich habe keine kinder.  


st -> ş  
sch -> ş  
sport -> şport

Verb in position 2:  

Frage:  
Wer ist das?  
Wie heißen Sie?  
Woher kommst du?  

Antwort / aussage  
Ich bin Paco.  
Ich komme aus Österreich.  
Mein Name ist Valerie.  








Lokale Pröpositionen + Dativ: Wo?

Imperativ -> Verb (1) + Subj + ...  
Trinken Sie (doch) Tee! -> doch ist höflich


emotion -> null artikel  habe angst  

*Nicht trenbare verben:*  
be-  
ver-  
er-  
ent-  
miss-  
zer-  
emp-  
ge-  













---

# Artikel




| **Artikel**                   | **Nominativ** | **Akkusativ**   | **Dativ**       |
| -----------------             | --------      | --------        | --------        |
| **bestimmter Artikel**        | der           | den             | dem             |
|                               | die           | die             | der             |
|                               | das           | das             | dem             |
|                               | die (Pl)      | die (Pl)        | den (Pl)        |
| **unbestimmter Artikel**      | ein (der)     | einen           | einem           |
|                               | ein (das)     | ein             | einem           |
|                               | eine (die)    | eine            | einer           |
| **Posseessiv Artikel "mein"** | mein (der)    | meinen          | meinem          |
|                               | mein (das)    | mein            | meinem          |
|                               | meine (die)   | meine           | meiner          |
|                               | meine (Pl)    | meine (Pl)      | meinen (Pl) + n |
| **Posseessiv Artikel "dein"** | dein          | deinen          | deinem          |
|                               | deine         | deine           | deiner          |
|                               | dein          | dein            | deinem          |
|                               | deine (Pl)    | deine (Pl)      | deinen (Pl)     |
| **Posseessiv Artikel "sein"** | sein          | seinen          | seinem          |
|                               | sein          | sein            | seinem          |
|                               | seine         | seine           | seiner          |
|                               | seine (Pl)    | seine (Pl)      | seinen (Pl)     |
| **Posseessiv Artikel "ihr"**  | ihr           | ihren           | ihrem           |
|                               | ihr           | ihr             | ihrem           |
|                               | ihre          | ihre            | ihrer           |
|                               | ihre (Pl)     | ihre (Pl)       | ihren (Pl)      |



der / ein / kein  
die / eine / keine  
das / ein / kein  



**Personal Pronomen**  
ich du er sie es wir ihr sie Sie


| **Definit Artikel**           | **Indefinit Artikel** | **Personal Pronomen** |
| -----------------             | --------              | --------              |
| der Schrim                    | Das ist ein Schrim    | Er ist grün           |
| das Buch                      | Das ist ein Buch      | Es ist rot            |
| die Uhr                       | Das ist eine Uhr      | Sie ist braun         |





---

# Frage {.tabset .tabset-fade .tabset-pills}




---

## W frage {.tabset .tabset-fade .tabset-pills}

Hallo.  
Wie heißen Sie? Ich heiße ...
Freut mich. Freut mich auch.

Wer bist du?  

Wer ist das? Das ist ...

Wie ist Ihr Vorname? Mein Vorname ist ...

Wie ist Ihr Familienname/Nachname?
Mein Familienname ist ...

Woher kommen Sie? Ich komme aus ...

Wo wohnen Sie? Ich wohne in ...

Wo alt bist du? Ich bin ... Jahre alt.




---

### Was 

Was ist seine Telefonnummer? Meine telefonnummer ist ...

Was heißt seine Deutschlehrerin? Wer ist seine Deutschlehrenin? Meine Deutschlehrenin heißt ...

Was ist das? Das ist ein Buch. Das sind zwei Bücher.






---

### Wo

Ich suche die Disco. Wo ist sie, bitte?  
Sie ist neben das Museum.  

Wo ist die Maus?  

Wo arbeitest du?  
Wo arbeiten Sie?  
Ich arbeite bei ...  







---

### Wer

- Wer bist du?  
- Ich bin ...

- Wer sind Sie?  
- Ich bin Herr/Frau ...

- Wer kennt Brad Pitt?  
Ich kenne Brad Pitt.  








---

### Wie

- Wie heißen Sie?  

- Wie geht's dir?  
Wie geht es dir?  

- Wie geht's Ihnen?  
Wie geht es Ihnen?  
Danke, sehr gut. Und Ihnen?


- Danke sehr gut / super / toll
gut/prima  
es geht  
nicht so gut  
schlecht  


- Wie bitte?  

- Wie alt sind Sie?  
- Wie alt bist du?  
Ich bin zwanzig Jahre alt.












---

### Wie viele

Wie viele Tische sind hier? (Frage)    
Hier sind fünf Tische. (Antwort)  

Wie viele kinder haben Sie?  
Wie viele kinder hast du?  
Ich habe ein kind.  










---

### Woher

Woher kommst du? (informell)  
Woher kommen Sie? (formell)  
Woher kommt sie?  
Woher kommt er?  
Woher kommen Sie?  

kommen + aus + land/stadt  
Ich komme aus Mexiko  
Sie kommt aus Deutscland  
Er kommt aus Frankreich  
Sie kommen aus Spaninen  
der Türkei  
der Schweiz  
dem Iran  
dem Irak  












---

### Welche

Welche Sprachen sprechen Sie? Ich spreche gut Türkisch, flueßen Englisch und ein bisschen Deutsch.












---

### Wem

Wem gehört die Uhr?  
Die Uhr gehört ihm.

Wem gehören die Bücher?  
Die Bücher gehören ihm. 











---

## Ja-Nein Frage

Sind Sie verheiratet?  
Ja, ich bin verheiratet.  
Nein, ich bin nicht verheiratet.  
Nein, ich bin ledig.  

Haben Sie Kinder?  
Hast du Kinder?  

Ja, ich habe ein kind.  
Nein, ich habe keine kinder.  


Kennen Sie Brad Pitt?  
Ja, ich kenne Brad.
Nein, ich kenne Brad nicht.  


Hast du kein Kinder?  
Doch, ich habe zwei kinder.  
Nein, ich habe keine kinder.  










---

# Bildwörter {.tabset .tabset-fade .tabset-pills}

## Körper und Gesundheit

der Körper  
der Kopf | die Köpfe  
die Brust | die Brüste (göğüs)  
das Bein | die Beine  
der Fuß | die Füße  
der Hals | die Hälse (boyun)  
der Bauch | die Bauche (batın)  
das Kine | die Knie  
der Zeh | die Zehen (Toe)  
der Rücken (bel)  
die Schulter | die Schulterin (omuz)  
der Arm | die Arme  
der Ellbogen | die Ellbogen (dirsek)  
der Po | die Pos  
die Hand | die Hände  
der Finger | die Finger  
das Gesicht | die Gesichter  
das Haar | die Haare  
die Nase | die Nasen  
der Mund | die Münder  
die Lippe | die Lippen  
der Zahn | die Zähne  
die Zunge | die Zungen  
das Ohr | die Ohren  
das Auge | die Augen  


die Seife | die Seifen  
das Shampoo | die Shampoos  
das Handtuch | die Händtucher  
die Zahnbürste | die Zahnbürsten  
die Zahnpasta | die Zahnpastas die Zahnpastas  
die Creme | die Cremes  

der Schmerz | die Schmerzen  
das Fieber  
das Blut  
das Pflaster | die Pflaster  
das Medikament | die Medikamente  
die Tablette | die Tabletten  
der Arzt | die äzte  
die ärztin | die ärztinnen  
die Krankenschwester  
der Patient | die Patienten  
die Patientin | die Patientinnen  
die Versichertenkarte | die Versichertenkarten  
die Praxis | die Praxen  
das Krankenhaus | die Krankenhäuser  
der Krankenwagen die Krankenwagen  


duschen | hat geduscht  
baden | hat gebadet  
sich kämmen | hat sich gekämmt  (comb hair)  
sich rasieren | hat sich rasiert (shave)  

gesund | gesünder | am gesündesten  
krank | kränker | am kränkesten  
tot  


## Kleidung

die Kleidung  
die Hose | die Hosen  
der Rock | die Röcke (etek)  
das Kleid | die Kleider  
die Bluse | die Blusen  
das Hemd | die Hemden (gömlek)  
der Anzug | die Anzüge (takım elbise)  
die Krawatte | die Krawatten  
das Kostüm | die Kostüme  
der Pullover | die Pullover (kazak)  
die Weste | die Westen (cepken)  
das T-shirt | die T-shirts  
die Jeans | die Jeans  
die Jacke | die Jacken  
der Mantel | die Mäntel  
die Mütze | die Mützen (bere)  
der Handschuh | die Handschuhe  
der Schal | die Schals die Schale (atkı)  
der Gürtel | die Gürtel (kemer)  
der Schuh | die Schuhe  
der Stiefel | die Stiefel (çizme)  
der Strumpf | die Strümpfe (çorap)  
das Unterhemd | die Unterhemden (atlet)  
die Unterhose | die Unterhosen  
der Unterrock | die Unterröcke  

sich ausziehen | hat sich ausgezogen (soyunmak)    
sich anziehen | hat sich angezogen (giyinmek)  


## Essen und Trinken

der Hunger  
der Durst  

essen | hat gegessen  
trinken | hat getrunken  
frühstücken | hat gefrühstück  


satt (tok)  


das Frühstück | die Frühstücke  
das Mittagessen | die Mittagessen  
das Abendessen | die Abendessen  
die Lebensmittel (erzak)  
die Butter  
der Käse | die Käse  
die Wurst | die Würste  
das Ei | die Eier  
das Mehl (un)  
der Pfeffer  
das Salz  
der Zucker  (şeker)  

das Obst (meyve)  
der Apfel | die äpfel  
die Birne | die Birnen  
die Orange | die Orangen  
die Traube | die Trauben (üzüm)  
die Banane | die Bananen  
die Zitrone | die Zitronen  
die Ananas | die Ananas / die Ananasse  
die Kirsche | die Kirschen  (kiraz)  
die Pflaume | die Pflaumen  (erik)  
die Aprikose | die Aprikosen  (kayısı)  
die Erdbeere | die Erdbeeren  (çilek)  
die Himbeere | die Himbeeren  (redberry)  
die Brombeere | die Brombeeren (blueberry)  

das Gemüse | die Gemüse (sebze)  
die Aubergine | die Auberginen (patlıcan)  
die Paprika | die Paprika die Paprikas
der Spinat    
die Bohne (fasülye)  
die Erbse | die Erbsen (bezelye)  
die Karotte  
der Mais (mısır)  
die Kartoffel | die Kartoffeln  
die Tomate | die Tomaten  
die Gurke | die Gurken (salatalık)  
die Zwiebel | die Zwiebeln  (soğan)  
die Zucchini | die Zucchini  (kabak)  
der Pilz | die Pilze (mantar)  
die Nuss | die Nüsse (ceviz)  
der Salat | die Salate  
das Öl | die Öle  
der Essig | die Essige (sirke)  
die Nudeln  
der Reis  

der Fisch | die Fische  
das Fleisch  
das Geflügel  (tavuk)  
das Brot | die Brote  
das Brötchen | die Brötchen  
der Kuchen | die Kuchen (kek)  
die Suppe | die Suppen  
die Pommes frites  

die Schokolade | die Schokoladen  
das Eis | die Eis (dondurma)  
die Getränke  
das Bier | die Biere  
der Wein | die Weine  
der Kaffee | die Kaffes  
der Tee | die Tees  
die Milch  
der Saft | die Sãfte  


das Glas | die Glãser  
die Flasche | die Flaschen  
das Geschirr (tabak çanak)  
die Tasse | die Tassen (fincan)  
die Untertasse | die Untertassen  
der Teller | die Teller (tabak)  
das Besteck | die Bestecke (çatal bıçak)  
das Messer | die Messer (bıçak)  
die Gabel | die Gabeln (çatal)  
der Löffel | die Löffel (kaşık)  
der Teelöffel | die Teelöffel  

der Geschmack | die Geschmãcke (tat)  

sauer | saurer | am sauresten (ekşi)  
süß | süßer | am süeßten (tatlı)  
scharf | schãrfer | am schrãfsten (acı)  
salzig | salziger | am salzigsten (tuzlu)  

die Küche | die Küchen  
der Herd | die Herde (ocak)  
der Ofen | die Öfen (fırın)  

kochen | hat gecoht  
backen | hat gebacken

das Restaurant | die Resraurants  
der Kellner | die Kellner (garson)  
die Kellnerin | die Kellnerinnen  
die Speisekarte | die Spaisekarten (yemek listesi)

bestellen | hat bestellt  (sipariş vermek)


## Die Farben

die Farbe | die Farben  

rot  
gelb  
blau  
grün  
braun  
grau  
schwarz  
weiß  
rosa  
orange  
lila  


## Gebãude und Wohnen  

die Stadt | die Stãdte  


















## Anderes

Angelas Buch  
Sie ist Angelas Kind.  
Das ist Julias Buch.  
Das ist Yunus' Buch.  
Das ist Aziz' Buch.  

Herkunff  

Ich wohne in Kizilay in Ankara in der Turkei.

Ich lerne Deutsch.  
Wir lernen das Alphabet.  

Kann ich Sie etwas fragen?



## Sprache

Sprache | Sprachen  
Deutsch  
Türkisch  
Englisch  

Ich spreche sehr gut Deutsch. (100%)  
Ich spreche gut / fließend Englisch und Türkisch. (80%)  
Ich spreche ein bisschen Spanisch. (20%)  


Welche Sprachen sprichst du?  
Welche Sprachen sprechen Sie?  

Ich spreche Deutsch.  
Englisch  
Italienisch  
Spanisch  
Französich  
Dänisch  
Niederländisch  
Belgisch  
Polnisch  
Russisch  
Arabisch  
Chienesisch  

Deutsch ist meine Muttersprache.  

die Fremdsprache  





## Familie

Eheman + Ehefrau -> Ehepaar  
Enkel + Enkelin -> Enkelkinder  

Familie  
Eltern  
Opa  
Schwester  
Mutter Mama  
Vater Papa  


| Maskulin | Feminine | Plural |
| --- | --- | --- |
| mein | meine | meine |
| dein | deine | deine |
| Vater | Mutter | Eltern |
| Sohn | Tochter | Kinder |
| Bruder | Schwester | Geschwister |
| Großvater | Großmutter | Großeltern |  

meine Eltern  
meine Enkelin
meine Familie  


Bruder | Brüder  
Tochter | Töchter  
Sohn | Söhne  
Enkel | Enkel  
Familie | Familien


Wie ist deine Telefonnummer?  
Wie ist Ihre Telefonnummer?  

Familienmitglied (Family member)  

Wie heißt Ihre Mutter?  
Wie heißt deine Mutter?  

Was macht sie Beruflich?
Was macht deine Mutter Beruflich?

Wie alt ist deine Mutter?  

Wo wohnt deine Mutter?  

Ist deine Mutter verheiratet?  

Wie viele kinder hat deine Mutter?  







## Familienstand

Vorname  
Familienstand  

Ich bin verheiratet.  
Sie ist verheiratet.  
ledig (bekar)  
verliebt (sevgili)  
verlobt (sözlü/nişanlı)  
verheiratet (evli)  
geschieden (boşanmış)  
verwitwet (dul)  












---

## Beruf

Ich bin + Beruf  
Ich arbeite als + Beruf (iş)  
Ich arbeite bei + Firma  
Ich arbeite bei + Arbeitgeber (işveren)  

Was sind Sie von Beruf?  
Was bist du von Beruf?  

Was machen Sie Beruflich?  
Was machst du Beruflich?  


Was studieren Sie?  
Was studierst du?  

Ich studiere Musik auf lehramt.  
Physik  
Mathemtaik  

Ich bin arbeitslos.  (işsiz)  

Ingenieurwesen  
Wirtschaftswissenschaften  
Rechtswissenschaften  
Biologie  
Chemie  
Naturwissenschaft  

Ich bin Student / Studentin. Universität  
Ich bin Sculer / Schülerin. Schule  

ein Praktikum machen  
Ich mache ein Praktikum bei ... / als ...  

eine Ausbildung machen (a long education)  
Ich mache eine Ausbildung bei ... / als ...

Ich habe einen Job als (Beruf) bei (Firma)  

Anwalt | Anwältin (avukat)  
Biologe | Biologin

Kriminalrecht  
Studentiche Hilfskraft  
Bauingeniur  
Ingeniurweiss  
Biomedizin  











---

## der Kalendar

die Woche  
der Tag  
das Jahr  
die Stunde  
die Minute  
der Monat  








---

## weg  

Bitte links abbiegen  
Bitte rechts abbiegen  
Gehen/Fahren Sie geradeaus  
Bitte wenden Sie  
An der Ampel fahren Sie geradeaus  
Gehen/Fahren Sie an der Kirche vorbei  
Gehen/Fahren Sie die zweite Straße links  

erste  (first)  
nächste  (next)  
zweite  (second)  
dritte (third)  

einbahnstraße  
















---

# Lokale Präpositionen

Lokale Pröpositionen + Dativ: Wo?

**der -> dem  das -> dem  die -> der die(Pl) -> den + n**


der Würfel:  
Die pyrmide ist auf dem Würfel.

das Haus:  
Der Würfel ist neben dem Haus.

die Pyramide:  
Der Würfel ist neben der Pyramide.

die Häuser (Pl.):  
Das Auto ist zwischen den Häusern.

die Pyramiden (Pl.):  
Das Auto ist zwischen den Pyramiden.  
Das Auto ist zwischen den Taxis.  


in dem -> im  

das Café | die Cafés  

Die Frau ist in dem Café.  (Özellikle vurgulanmak istenirse bu da kullanılabilir)  
Die Frau ist im Café.  


an dem -> am  

Die Lehrenin ist an dem Tisch.  
Die Lehrenin ist am Tisch.  

Ali stieht am Fenster.  

die Wand | die Wände  

Der Kalender ist an der Wand.  
Der Kalendar hängt an der Wand.  







Ich suche die Disco. Wo ist sie, bitte?  
Sie ist neben das Museum.  

Wo ist die Maus?  
Die Maus ist vor dem Käse.  
Die Maus ist auf dem Käse.  
Die Maus ist neben dem Käse.  
Die Maus ist hinter dem Käse.  
Die Maus ist zwischen dem Käse.  
Die Maus ist an dem Käse.  
Die Maus ist unter dem Käse.  
Die Maus ist in dem Käse.  
Die Maus ist über dem Käse.  


Auf dem Sofa schläft ein Mann
Vor dem Sofa ist ein Teppich  
Auf dem Teppich ist ein kleiner Tisch  
Unter dem Tisch ist eine Tasche  
Hinter/ Über dem Sofa ist ein Bild  
Neben dem Sofa ist ein Laptop  

Wo ist der Stab?


---

# Zeitpräpositionen















---

# Zahlen 0 bis 30

0 null
1 eins (ei -> ai)
2 zwei (z -> ts)
3 drei
4 vier (ie -> ii)
5 fünf
6 sechs
7 sieben
8 acht
9 neun (eu -> oi)
10 zehn (eh -> ee)
11 elf
12 zwölf
13 dreizehn
14 vierzehn
15 fünfzehn
16 sechzehn
17 siebzehn
18 achtzehn
19 neunzehn
20 zwanzig
21
22
23
24
25
26
27
28
29
30
40
50
60
70
80
90
100 ein hundert

34
43
52
61
75
86
97





---

# Zahlen

100 (ein)hundert
101 (ein)hunderteins
200 zweihundert
300 dreihundert
400 vierhundert
500 fünfhundert
600 sechshundert
1000 (ein)tausend
2000 zweitausend
10000 zehntausend
20000 zwanzigtausend
100000 (ein)hunderttausend
1000000 eine Million

248999 | zweihundertachtundvierzigtausendneunhundertneunundneunzig















---

# gleich

plus  +  
minus  -  
mal  *  
durch  /  
ist/gleich =  

1+1 = 2 eins plus eins ist / gleich zwei  










---

# Gegenteil

öffnen X schließen

Ich öffne das Buch. Ich schließe das Buch.

die Nähe  X die Ferne  

Was ist das Gegenteil von groß?  
Das Gegenteil von groß ist klein.  




groß X klein  
Schön X Hässlich  
Schauer X leicht  
Lang X kurz  















---

# Kurssprache


- Schreiben Sie Bitte  
- Sprechen Sie Bitte  
- Buchstabieren Sie Bitte  
- Fragen Sie Bitte  
- Öffnen Sie die Bücher bitte  
- Scließen Sie die Bücher bitte  
- Hören Sie bitte  
- Zählen Sie bitte  (to count)  
- Antworten sie bitte  
- Stehen sie bitte auf  
- Schaun Sie bitte  
- eine moment bitte  
- Konjugieren Sie bitte  
- Ich habe eine Frage  
- Lesen Sie bitte  
- Ordnen Sie bitte zu  (Order)  
- Kontrollieren Sie bitte
- Merkieren sie bitte  
- Was heißt "...." auf Deutsch?  
- Was ist das Gegential von "..."?  
- Was ist der Artikel von ... ?  
- Entschuldigung  
- Wie schreibt man ... ?  
- Wie geht's ihnen?  
Mir geht's gut.  
Danke, gut.    
- Wie heißt die Pluralform von ... ?  
Die pluralform von Tache heißt/ist Taschen.   
- Wie heißt der Plural von ... ?  
Der Plural von Tasche ist/heißt TAschen.  
- Können Sie das lesen?  
- Wie bitten Sie um Hilfe?  
- Ich verstehe das nicht.  
- Wie schreibt man das?  
- Was heißt das?  
- Wie spricht man das aus?  
- Was wollen wir tun?  (tun -> machen, What should we do?)  
- Bitte helfen Sie mir.  



---

# Anderes


Wie waren Ihre Feiertage?  
Wie waren deine Feiertage?  

Meine Feiertage waren schön.  

Was haben Sie gemacht?



---


# A1 {.tabset .tabset-fade .tabset-pills}


---

## 1

https://hueber.de/shared/uebungen/menschen/kb/a1/livebook/l01/index.php


Wer ist das ?
 +Das ist Ayşe/Frau Öztürk
         |vorname|  |familienname|

Wie ist ihr Vorname ?
 +Meine Vorname ist....
 
Wie ist ihr Familienname
            Nachname
 +Mein Familienname ist...
 
 Wie heißen Sie ?
 +Ich heiße ...
  -Freut mich
   -Freut mich auch
   
 0-null  
 1-eins
 2-zwei
 3-drei
 4-vier
 5-fünf
 6-sechs
 7-sieben
 8-acht
 9-neun
 10-zehn
 11-elf
 12-zwölf
 .
 .
 15-fünfzehn
 16-sechzehn
 17-siebzehn
 18-achtzehn
 19-neunzehn
 20-zwanzig
 
 Arbeitsblatt- çalışma sayfası
 
 Was ist das ?
  Das ist ein Buch
  Das sind zwei Bücher
  
  Ich öffnen das Buch
  Ich schließe das Buch

-Stadt-Stadte

-Hello ,wer bist du ? - informell
  Ich bin Simone
  
-Wer sind Sie ?
  Ich bin Simone H....
  
 Woher kommen Sie ?
 
 Woher kommst du ?
 
W-Fragen V 2 position
          -Wer ist das ?
           Wie heißen Sie?
           Woher kommst du?

Antwort/Aussage

Buch Bücher
Lehrerin Lehrerinnen
Lehrer  Lehrer
Kursteilnahmerin  Kursteilnehmerinnen
Kursteilnehmer  Kursterilnehmer
Fenster Fenster
Tisch Tische

Wie viele Tische sind hier?
-Hier sind .... Tische

kommen + aus + Land/Lander Stadt Stadte

Ich komme aus Spannien
              -der Turkei
              -der Schweiz
              -dem Iran
              -dem Irak

Personalpronomen kommme/komsst/kommen/kommt

Woher kommt sie/er ?
*Sie kommmen

Wie geht's dir ?
    geht es
    
Wie geht's Ihnen
    geht es
    
Danke |sehr gut/super/toll
       gut/prima
       es geht
       nicht so gut
       schlecht

kommen    heißen
komme     heiße
kommst    heißt
kommen    heißen
kommt     heißt

Wie bitte ?


              
  
  



---

## 2


Ich wohne in ....

            Beruf

Mann- Manner
Frau-Framen
Visitenkarte-Visitenkarten
Beruf-Berufe

Ich bin + *Beruf

Ich arbeite als + *Beruf

Ich arbeite bei + *Firma Arbeitgeber

Was sind Sie von Beruf ?
    bist du
    
Was machen Sie beruflich ?
    machst du
    
*arbeiten
arbeite/arbeitest/arbeitet/arbeiten

KONJUGİEREN SİE BİTTE

Was machen Sie beruflich ?
  Ich bin Student
  
Was Studieren Sie ?
    Studierst du ?
 Ich Studiere Musik auflehramt.
                    Ingenieurwesen.
                    
Ich bin arbeitslos.
        Wirtshaftswissenschaften- BWL
        Rechtswissenschaften
        Biologie
        Chemie
        Naturwissenschaften
        Biologe/Biologin
        Anwaltin/Anwalt

ein Praktikum machen
Ich mache ein Pratikum. bei .... / als..

eine Ausbildung machen
Ich mache eine Ausbildung bei.../als...

REGEL einen Job haben / als Beruf
                        bei Firma
                        
                        
st---->şt
sch---->ş
sp---->şp

27-siebenundzwanzig
30-dreißig
21-einundzwanzig
22-zwaiundzwanzig
34-vierunddreißig
43-deriundvierzig

Wie alt sind Sie?
        bist du?
        
 Ich bin ... Jahre alt.
 
ledig
verliebt
verlobt
verheirotet
verheirotet
geschieden
verwitwet

Bist du verheriratet ?
Sins sie verheiratet

 Ja,Ich bin vergeiratet
 Nein,Ich bin nicht verheiratet
 Nein,Ich bin ledig.

sein
Ich *bin
du  *bist
Sie *sind
er/Sie *ist

leben      wohnen
*lebe      *wohne
*lebst      *wohnst
*leben      *wohnen
*lebt       *wohnt

Ich habe ein kind / Kinder

Wie viele Kinder haben Sie ?
                 hast du ?
                 
Haben Sie Kinder?
Hast du Kinder ?

keine  Ja, Ich habe ein kind.
       Nein,Ich habe keine kinder.









---

## 3


Wo arbeiten Sie ?
   arbeite bei Siemens
   
   
Jahr-Jahre


Simones Buch
Emirs Buch
Yunus' Buch
Aziz' Buch

kennen
*kenne
*kennst
*kennt
*kennen
*kennt
*kennen

Drehbuch
Ausschnitt

Kennen Sie Brad Pitt?

Wer kennt Diester Bahlen ?

Possesivartikel
     maskulin feminin Plural
Ich   mein    meine   meine
du    dien    deine   deine

Vater / Mutter / Eltern
Sohn/Schwester/Geschwester
Großmutter/ Großfather/Großeltern

Bruder/Tochter/Enkelin
(Ehe)Mann / (ehe) Frau

Vater+Mutter=Eltern
Sohn+Tochter=Kinder
Bruder+Schwester=Geschwester
Großvater+Großmutter=Großeltern
Enkel + Enkelin=Enelkinder
Ehemann + Ehe frau = Ehepaar-singular

Brüder Brüder
Tochter Töchter
Sohn    Söhne
Enkel   Enkel
familie  familien

Kommen Sie nich aus Ankara ?

+ Doch Ich komme aus Ankara.

-Nein Ich komme nich aus Ankara.

Kommen Sie aus Ankara ?

+Ja, Ich komme aus Ankara
-Nein, Ich komme nicht aus Ankara

Position 2

W-Frage -Woher kommen Sie ?
Aussage -Ich komme aus Ankara.

                  -Antwort=Nein
Regel  +Frage     +Antwort=Ja
       -Frage     -Antwort=Nein
                  +Antwort=Doch
                  

---

## 4


Möbel  
Tisch  
Lampe  
Bett  


Ich glaube Sie sind (nicht) verheiratet.

Möbelhaus (like IKEA)

Das bild kostet 15 €. Das ist billig.  
Das bild kostet 1000 €. Das ist teuer.  

Brauchen Sie hilfe?  
Ja, bitte.  
Nein, danke.  

Wie viel kostet der Tisch?  
Was kostet der Tisch?  

der Preis  
der Fernsheer  

Der Tisch kostet 1478 € | eintausendvierhundertachtundsiebzig euro


Die Couch  
Die Couch kostet ...
Sie kostet ...
Sie kommt aus Italien.  
Sie ist sehr teuer.  


Materialen  
das Holz  
das Metall  
das Glas  
das Popier  
der Kunstoff  
das Plastik (die Plastik sanat eserleri için kullanılır)

Farben  
rot
grün
orange
schwarz
blau
gelb
weiß
braun

Formen
echig (köşeli)
rund
sternfürmig (starshaped)
wolkenformig (bulut şekli)

der stern
die Wolke  

aus + Material (keine artikel)  
Frau Klums Brille ist aus Kunststoff.  
Das ist Pinocchio. Er ist aus Holz.  
Die Flasche ist aus Plastik.  

verkaufen  



Das ist Brille von Top-Designerm S.A.H
Die Brille ist stemförmig,blau-gelb und aus Plastik
Mein Goethe-Sonderundebot nur 21 Euro.

das Etikett
der Zustand
Versteigern
neu gebraucht
Ich bieten ....!

Wie schreibt man ?
Wie heißt das auf Deutsch.

Entsculdigung , Wie heißt das auf Deutsch ?

Definitartikel |  Indefinit artikel   | Personelpronomt

Der Schrim        Das ist ein Schrim    Er ist grün   (m)
Das Buch          Das ist ein Buch      Es ist rot    (n)
Die Uhr           Das ist eine Uhr      Sie ist braun (f)

einmal benutzt ---1 kez kullanılmış

*durchsichtig

der (Regel) Schrem
das Streichholz
die Geldbörse
die Seife
der Bleistift
die Brille
das Buch
die Flasche
das Feuerzeug
der Fotoapparat
die Katte
der Kugelschreiber
der Schüssel
die Tasche



---


## 5



*ausweis
*mit freundlichen grüßen

Wie geth's ?
-Mir geht's gut.

die Zeitung--ung--->DİE

Auktion
rückwärts
s Meer
e Freundin,nen
r Freund,e
e Kollegin,in
bestellen
e Bestellung
r Kollege,n
r Chef,s
e Chefin,nen
e Postwärts
r Arbeitsplatz
r Platz
glücklich
Termin

Wie heißt die Plural form von ... ?
          der Plural


Die Pluralform von Tache heißt/ist Taschen
Der Plural

zigaretten rauchen
wasse trinken

Namen + Verb kombinotion

Wer sucht Rechnungen ?

Wer braucht Stiftel ?

Was ist das Handy ?

Wo sind die Handys ?

Wo ist denn der Schlüssel ?
Wo ist der Schlüssel ?
       die Maus ?
       das Formular ?
       
Hier ist der Schlüssel.
         die Maus.
         das Formular.


Hier sind die Formulare.


Wo sind die Schlüssel ?
+Hier | ist | die | Tasche   |
      |verb |     | Subjeckt |

Was suchen Sie ?

+Ich suche das | Kursbuch |.
               | Objekt   |
               
Ich suche | den Schlüssel
          | die Maus
          | das Formular.

der---->den  den Laptop
             die Briefmarke
             das Formular
             

Alle subjekte sind immer im Nominativ.

  *Der schlüssel ist klein. Was
  *Die Lahrerin ist groß. Wer

Verben+ Akkusativ

öffnen 
machen
schließen
hören
schreiben
sprechen
haben
finden
suchen
lesen
markieren
buchstabieren
fragen
brauchen
lieben
konjugieren
ergänzen
finden
schreiben

Ich haben den Schlüssel.
    suche
    finde


Was suchst du ?
Ich suche den Lehrer. Wen ?

Wen suchst du ?
Ich suche den mann.

Du suchst den Laptop 
Den Laptop suchst du.

Ich brauche den Laptop
            einen Laptop
            
    Nominativ    Akkusativ
Der| kein      |    keinen|
Die| keine     |    keine |
Das| kein      |    kein  |
Die| keine     |    keine |
            
            
Wie viele ... haben Sie ?

Ich habe ..... ein
               kein
               eine
               keine
               einen
               keinen
               
---



## 6



| Sich meiden  |  Sich meiden             | Sich verabschieden
| --- | --- | --- |

| Firma + Name | Guten Tag                | Tschüss
|             |  hier ist Marlene Neumann|Auf Widerhören
|             |  Hallo hier ist ....     |Auf widersehen


Das Gewitter
der Donner
der Blitz
der Regen
das Stück,e
der Autor,en
handeln
gebraucht
der Trödel,-
der Trödler,-
der Trödlerin,nen
der Koch,"e
die Köchin,nen
-kochen

Spazieren gehen
Rad Fahren
Scach spielen
Musik hören
Freunde treffen
lesen
fotografieren
schwimmen
Im ınternet surfen
singen
kochen
schnellxlangsam
Postkarte
Händler
Teller
Tasse
Handtuch
König
Puppe
Schlüsselanhänger
der Nachtflohmarkt
Nummer eins
Sachsen

Du kannst wirklich gut Tenis spielen
-Sie können gut Tennis spielen

Wow! Du kannst ja super tanzer.
-Sie können super tanzen.

Du kannst wirklich toll kochen.
   
*Modalverb 2. ---------- Infinite   

 *Du kochest sehr gut.
 
können
Ich kann
du kannst
er/sie kann
wir können
ihr könnt
sie/Sie können

Du spielst wirklich gut Gitarre.
Du kann wirklich gut Gitarre spielen.

Was sind deine Hobbys ?
         ihre  Hobbys ?


Was ist dein Hobby ?
        Ihr  Hobbys ?
        
        
Meine Hobbys sind fußball spielen
Mein Hobby ist singen,Basketball spielen.



---



## 7


tauchen
die Harpune,n
Jagen
die Brücke,n
Lösung
der Ausflug,"e
einen Ausflugmachen

fußball spielen macht Spaß!
kochen macht  Spaß!

Klavier Spielen Lieblingsänger.
  Fahren Sie gern Ski ?
  Fährst du
  
  +Ja , Ich fahre gern Ski.
  -Nein,Ich fahre nicht gern Ski.
  
  Verben mit lokol wechsel
  
| **verb**      | **ich**     | **du**      | **er/sie/es**   | **wir**     | **ihr**     | **sie/Sie**     |
|---            |---          |---          |---              |---          |---          |---              |
| *fahren*      | fahre       | fährst      |   fährt         | fahren      | fahrt       | fahren          |
| *lesen*       | lese        | liest       | liest           | lesen       | lest        | lesen           |
| *treffen*     | treffe      | triffst     | trifft          |   treffen   | trefft      | treffen         |
| *sprechen*    | spreche     | sprichst    | spricht         | sprechen    | sprecht     | sprechen        |
| *sehen*       | sehe        | siehst      | sieht           | sehen       | seht        | sehen           |

Ich spiele gern Gitarre.Ich arbeite gern.

Was machst du in der Freizeit ?
    machen Sie
   Leider habe ich kein Zeit
   Ich habe lider keine Zeit.
   Am wochende habe ich .....
    
Ich spiele gern Gitarre.
Ich backe gern
Ich arbeite gern
Ich mache gern Hausofgaben.

Fährst du gern Rad ?
Liest du gern Bücher ?
Triffst du gern Freunde ?

Wie oft gehst du ins Theater.
+Ich gehe |immer| ins Theater.
          |-----|
          |oft|
          |manchmal|
          |fast nie|
          |nie|
          
der Würfel
würfeln -zar atmak
das Wörterbuch,"es
die Pantomime,n
Möglichkeit

Können Sie bitte die Fenster öffnen.
Kann ich mal telefonieren ?
Kann ich das feuerzeug haben ?
Leider habe ich doch keine zeit .
Können Felix und Katja kochen ?
  +Ja,felix und Katja können super kocher.
  
nicht so gut    
super
toll ein bisschen
nicht so gut
nicht
gar nicht


senkrecht
waagerecht ---->>>
diagonal

Spielst du sehr oft fußball ?
  +Ja,Ich spiele sehr oft Fußball ?
  -Nein,Ich spiele nur manchmal fußball.

Wie oft schwimmst du ?
+Ich swimme fast nie.



---

## 8

Ich kann Bücker lesen.
Ich lese leiber.
Kannst du Schach spielen.
Ich verstehe das nicht.
Wie shreibt man das.
Wie spricht man das aus ?
Was sollen wir tun ?
Bitte helfen Sie mir.



der Kalender
das Wochenende,n
das Ende,n
die Woche,n

Heute Nachmittag gehe ich ins Schwimbad.
---------------       ---       ------
   Wann ?             Wer?       Wohin ?

Regel Wohin ? ---->in+Akkusativ
    in + das = ins
    in + die = Kneipe
    in + den = Zoo
    
Wohin gehen Sie morgen Abend ?
  Ich gehe morgen ins Cafê
  morgen abend gens in -----> in den Zoo / in die Disk / ins Kino
  
  
Wohin gehen Sie gern ?

Haben Sie heute Nachmittag zeit ?
  -Nein , leider habe ich keine zeit.

Wie spät ist es ? -- formel
  Es ist 11:40 Uhr.

Es ist fünf noch sieben 7:05
Halb acht - 7:30


7:30 - Halb acht
8:30 - Halb neun
7:35- fünf nach
7:25- fünf vor halb acht
7:45- vietel vor acht
7:28- Kurz vor halb acht
7:32- Kurz nach halb acht
04:03 kurz nach vier


der Morgen
der Kurs,e
Fluss
Fußball


Weiß ich nach nicht---henüz bilmiyorum

|wissen|
|------|
| weißt|
| weiß |
|wissen|
|wisst |
|wissen|

Ich weiß nicht.
Ich weiß nicht was du meinst.


Lust Haben.....

Lust auf  Schwimmbad ?
          Kino ?
          Disco ?
          
Lust Haben .....
  +Ich habe Lust
  -Ich habe keine Lust
  
 Hast du Lust auf ?
 
 Möchtest du ins Schwimmbad gehen ?
 
 spät x früh
 
 um 19:99 Uhr
 am Montag
 am Dienstag
 am Mittwoch
 am Donnerstag
 am Freitag
 am Samstag   am
 am Sonntag   Wochanende
 
 Ich gehe am Montag um 19:00 ins Kino.
          ------------------  ------
              Wann ?          Wohin ?
              
              
              
 Subjekt + Verb +Zeit + Wohin/Ort
 
 einen Vorschlang machen -- öneride bulunmak
 
 reagieren
 E Reaktion,en
 R Vorschlang,"e
 +Passt es dir  | um 18:00 Uhr
                | am Montag ?
  

Hast du heute Nachmittag Zeit ?
Ja,Warum
-Wir könen heute Schach spielen
  -Lust auf Schach spielen.
  -Gehen wir ins Kino
  -Gehen wir ins die Ausstellung ?
  
  Ich habe keine Lust
  -Gehen wir ins Konzert ?
  Ka,wann denn ?
  Um acht Uhr.-Ich habe um 20:00 Uhr keine Zeit.Passt es dir um 18:00 Uhr
  -Okay
  
  Gehen wir am Wochenende tanzen ?
  
  schlafen gehen
  höflich
  unhöflich
  die Einladung,en
  eine Ausstellung
  
    Wann haben wir wieder Kurs.
    Am Mittwoch haben wir wieder Deutsch kurs.
    Am Wochenende ist kein Kurs.

am-------> Wochentage
          Tageszeiten
          
          
Am Abend/Morgen lerne ich gern Deutsch
**In der Nacht** spiele ich gern ....
Am Dienstagnacjmittag gehe ins Shimmbad


*etwas vorschlagen*
Vielleicht können wir morgen Abend ins Theater gehen.
Vielleicht könen wir später zusammen kaffee trinken.

Heute Nachmittag gehe ich ins Museum
Heute Nachmittag male ich.
Ich gehe heute Nachmittag ins Museum.

die Uhrzeit,en



  

---

## 9



Wieder ?

am Nachmittag oder in der Nacht ?

am Nachmittag um 14:00 Uhr.


Liebe**r** ....,
  hast du am Sonnertag zeit ? Können wir ski fahren gehen oder vielleicht können wir in die Bibliothek gehen.
  Leibe Grüße
  
  Viele Grüße
  Freundliche Grüße
  
  Sehr geehte**r** Frau Freundenburg
  
  der Onkel,-
  die tante,n
  der Kühlschrank,"e
  der Hunger
  der Durst
  der Pilz,e
  das Ei,er
  der Olive
  das Obst
  das Gemüse
  
  Er hat Hunre ?
  -Haben Sie Hunger
  -Hast Du
  
  Ich habe auch Hunger
  Nein Ich habe keinen Durst.
  
  Bist du durstig ?
          hungrig?
 +Ja,Ich bin durstig.
 -Nein,Ich bin nicht durstig.
 
 immer--%100
 fast immer--%85
 oft--%60
 manchmal--%50
 fast nie--%20
 nie--%0
 
 
 Ich esse gern = Ich mag
 
 Ich mag Schokolade
         Kucher
         
         
Ich mag keinen Hamburger Spinat.

schon=sehr früh (çok erken)
erst = sehr spüt ( çok geç)

Was möchten Sie essen ?
-Ich möchte eine Fischsuppe essen.

Er trinkt keinen kaffee.
-Sie einen kaffee ?
-Ich möchte einen kaffee trinken.
-Marie möchte heute Abend tanzen.

Was ist dein Lieblingsessen ?
-Mein Lieblingsessen ist .....

Nominativ - der -ein degişmiyor
Akusativ der-einen

Was isst du gein.

|möchten|
|-------|
|möchte|
|möchtest|
|möchte|
|möchten|
|möchtet|
|möchten|

|mögen|
|-------|
|mag|
|magst|
|mag|
|mögen|
|mögt|
|mögen|







---

## 10



das flugzeug
die Sonnenbrille,n
der Blindenstock,"e
der Gehstock,"e

Ich komme um 22 Uhr um zu Hause an. ankommen

Du kommst um 22 Uhr zu Hause an.

Er/sie/es kommt um 22 Uhr zu Hause an.

Ich kaufe im supermarkt ein.--einkaufen

Du kaufst im supermarkt ein.

Ich rufe dich an.--anrufen

Wann rufst du mich an ?

Regel konjugiere Verb  Prafix am
        Position 2      Ende 
        
        
Rufst du mich an ? -- Ja/Nein Frage

Wann rufst du ?
--Ich rufe die Lehrerin an

Hast du mich ab ?

Won holst du ab ?
--Ich hole dich ab ?
meine

Was halst du ab ?
-Ich hole das Paket ab.

Holst du mich ab ?

meinen Sohn
meine Frendin
eine Freundin
die Abfahrt
die Ankunft

Ich hole dich ab.
Ich hole meine Tochter ab
Ich hole Zeyeb ab.
Ich hole meinen Sohn ab.

Was brinst du
Wen bringst du

Mein Bus fährt um 21:00 Uhr ab.

Mein/Der Bus kommt um 21:00 Uhr am

Halbst du mich ab ?
Kannst du mich abholen ?

halst du mich ab ?
Ich habe dich ab 

Wen halst du ab ?

alle 20 minuten fährt dir S-Bahn

Wan sind wir an Flughafen ?
Wie heißt der nächste Halt ?

Vor sicht an der Bahnsteigkante Der Zug fährt ab.

Ich suche die U2 zum Olympiazentum.

Die Bahn fährt gerade am Bahnsteig 5 ein.

Steight ihr am Goetheplatz ein ?
x Wann telefonierst du mit Oma.
Heute Abend sehen wir fern.Kommst du auch ?
Wo steigt ihr um ?
x Bekomme ich bitte einen Kaffee ?
Vielleicht bringe ich am Samstag meine Freundin mit.
x Am Sonntag frühstüke ich erst um 12 Uhr.

x nicht trennbar
-trennbar

Wann kommst du an ?
-Ich komme um 12 Uhr 45 an

Wo steigst du ein ?
-Ich steige auf Gleis 10 ein.






---

## 11



Wohin ?
    In+Akkıstiv
    
Wo ?
    In + dativ
    die-->der

Wen ?
Wenn
die Nuss,"e

Wan fährst du zu Hause ab ?
-Ich fahre um 16:00 Uhr ab.

unsteigen
___________________________________________________________________________________________

| **Subject Verb**   | **-**   |  **-**   |
| ---                  | ---                           | ---               | 
| Ich fahre            |  täglich                      | mit  denn Fahrad  |
| Ich fahre            |  2 bis 3 mal die Woche        |zur Arbeit         |
| Ich fahre            |  nur am Wochenende            | zum Einkaufen     | 
| Ich fahre            |  fast nie                     | ins Cafê          | 
| Ich fahre            |  nie                          | Ins Kino          | 
          
___________________________________________________________________________________________

Wie oft ? Wohin ?

Gestern
  Ich habe Hausaufgaben gemacht
      hilfstverb        partizip 2
  Tempus=Perfekt
  
  Perfekt-->kommunikation


Ich habe Deutsch gelernt.
Wann hast du Deutsch gelernt ?

Hast du Deutsch gelernt. Ja/Nein Frage
___________________________________________________________________________________________

das Gleis
der Bahnof
der Flughafen
die S-Bahn
der Zug
die Straßenbahn
die U-Bahn
Der Bahnsteig
das Taxi
der Bus
die Haltestelle
das Flugzeug
der Koffer
die Tasche
das Gepäck

Mach's gut
Oass auf dich auf
Verkehrsmittel
Gepäck
am Bahnhof
das Fahrrad,"er
die Celli
das Cello
das Instrument,3
der Terminkalender,-
das Geschenk,e
___________________________________________________________________________________________





---

## 12



| **Frühling**   | **Sommer**   |  **Herbst**   | **Winter**    |
| ---            | ---          | ---           | ---           |
| Marz           |  Juni        | September     | Dezember      |
| April          |  Juli        | Oktober       | Januar        |
| Mai            |  August      | November      | Februar       |



Was haben Sie | letzten Freitag | gemacht
              | letzte  Woche   |
              | letztes Jahre   |


der Tag,e
die Woche,n
das Jahr,r
der Schulabschluss,'s
der Bachelor
der Bachelorprüfung,en
der Master
die Fachochschule,n
der Würfel
der Stab,'e
die Pyramide,n

 
 hatte
 ______
 
 ich hatte
 du  hattest
 er/sie hatte
 wir    hatten
 ihr    hattet
 wir    hatten
 
? Was haben Sie gestern gemacht?
  +Ich habe gestern Hausaufgabe gemacht

__________________________________________________________


Wo ist Sie ?
 Wie komme ich zum Bahnhof.

auf üstünde                                   NOMİNATİV                 DATİV
an yanında                                    der/ein Bahnhof     | vor  dem einem
neben yanında(temas yok)                      das/ein Resteurant  |      dem einem
vor önünde                                    die/eine Ampel      |      der einer
hinter                                        die/- Cafe's Hauser |      den - Hausern
zwischen
über
unter
in

in dem = im
an dem = am

Was ist das Hotel Marrhim ?
 +Das hotel ist neben der bank.
 
 LOKALE PRAPOSİHİMEN MİT DATİV
 
 regel PRASPOSİTON + ARTİKEL -R --->DEM
 
 Die Pyramide ist auf dem Würfel.
 Der Würfel ist neben dem Haus.
 Der Würfel ist neben der Pyramide.
 
 WO?-----> die--->der
 
 der Stadtplang,'e                                          rechts abbiegen
 die Strasse,n                                              wenden
 der Navigator,en                                           zurückfahren
 das Hotel,s                                                geradeaus fahren
 anmachen                                                   links abbiegen
 ausmachen
 die Stadmitte
 das Zentrum
 der Polizist,en
 die Polizistin,nen
 die Wand,'e

 Stimm+nicht ---->false
 
 Der Kalender hangt an der Wand(die Wand).
 Das Auto ist zwischen den Hausern.
 
 Wo?
 die-----> den+Nomen +'n'
 
 Die Frau ist in dem(im) Cafe'.
 
 Die Lehrerin ist an dem (am) Tisch.
 
 Egehan ist am Fenster
 
 Dann kommen Sie unter einer Brücke durch.(durchkommen)
 
 Maritim ist in dem(im) Zentrum ?

An den Cafe's fahren Sie

Bitte links abbiegen

Bitte rechts abbiegen
Gehen/Fahren Sie geradeaus
Bitte wenden Sie
An der Ampel fahren Sie geradeaus.
Gehen/Fahren Sie an der Kirche vorbei
Gehen/Fahren Sie die zweite Strasse links.





---


## 13

https://hueber.de/shared/uebungen/menschen/kb/a1/livebook/l13/index.php



das Auto | die Autos  
das Hotel | die Hotels  

die Straße | die Straßen  

der Navigator | die Navigatoren  
der Stadtplan | die Stadtpläne  


Beiden (çift)  
Fussgenger (yaya)    

suchen X finden  
stimmt (richtig)  
stimmt nicht (falsch)  


anmachen X ausmachen (turn on X turn off)

Ich mache den CD-Player an.  
Ich mache die Lampe an.  
Die Frau macht den Navigator an.  


rechts abbiegen (turn right)  
links abbiegen (turn left)  
wenden (U turn)  
zürückfahren (aksi yönde gidin)  
hindfahren  
geradeaus fahren (go directly)


Wo ist das Hotel M... ?  
Das Hotel ist neben der Bank.  

der Würfel | die Würfel (kutu, zar)  
der Stab | die Stäbe (silindir)  
die Pyramide | die Pyramiden  

Wo ist ... ?

Wo sind ... ?

Wo hängt der Kalender?
Wo hängen .. ?
Wo liegt der Stift?  
Wo liegen der Stift?  
sitzt  
sitzen  
steht  
stehen  


- neben dem Haus

| Nominativ | Dativ |
| --- | --- | --- |
| der Würfel | dem Würfel |
| die Pyramide | der Pyramide |
| das Haus | dem Haus |
| die Würfel | den Würfel | 


Können Sie bitte das Licht anmachen?  
Können Sie bitte das Fenster aufmachen?  


*Zuerst* + Verb + Subjekt  

*Zuerst* gehen Sie immer geradeaus und
*dann* gehen Sie links. ...  
*danach* + Verb + Subjekt  

forbeifahren (kein stop)  

 ... dann fahren Sie an den Cafés vorbei ... 




Ball 1 ist neben dem Schrank.

Ball 2 ist auf der Couch.

Ball 3 ist im Schrank.

Ball 4 ist unter der Couch.

Ball 5 ist zwischen der Couch und dem Schrank.

Ball 6 ist hinter dem Schrank.

Ball 7 ist über der Couch.

Ball 8 ist an dem Schrank.

Ball 9 ist vor der Couch.

Ball 9 ist auf dem Teppich.


- Können Sie mir helfen? Wo ist das Café "Glockner"?  
- Tut mir leid, ich bin fremd hier. / ich bin nicht von hier.  


- Ja, das ist gleich die nächste Straße links.  
- Vielen Dank, das ist sehr nett.  

- Oh, tut mir leid. Das weiß ich nicht.  
- Schade. Trotzdem: Dankeschön.  

- Kann ich Sie etwas fragen? ich suche den Bahnhof.  
- Fahren Sie zwei Kilometer geradeaus. Dann sehen Sie schon den Bahnhof.  

- Kennen Sie das Restaurant "Schönblick"?  
- Ja, das ist ganz in der Nähe. Wenden Sie hier und fahren Sie zurück bis zur Ampel und dann links.  





- Wo ist das Nationalmuseum?  
- Wie kann man dahin fahren/ gehen?  
- Was kann man noch in Ihrem Heimatland/ Ihrer Heimatstadt besuchen?  

Das Museum ist sehr nah/ weit vom Bahnhof.  
Da kannst zu Fuß gehen/ Da musst du den Bus oder die U-Bahn nehmen.  
Du gehst geradeaus bis zur (fem.) / zum (mask./neutrum) ...  
Dann gehst du die erste/zweite/nächste Straße links/rechts.  
Nach ... Metern findest du das Museum links/ rechts.  
Du nimmt den Bus oder die U-Bahn Nummer .... Du steigst an der Station .... aus.  


Sie können hier essen -> Restaurant  
Anderes Wort für Stadtmitte -> Zentrum  
Hier fahren Züge ab und es kommen Züge an -> Bahnhof  
Hier bekommen Sie Geld -> Bank  
Hier können Sie Briefmarken kaufen -> Post  
Rot: Sie bleiben stehen. Grün: Sie können fahren -> Ampel  
Hier können Sie einen Tee oder Kaffee trinken --> Café  
 


Anzeige  
Schöne 2-Zimmer-Wohnung frei ab 1.5.  
45 Quadratmeter mit großem Balkon  
Möbliert, mit Stellplatz in der Tiefgarage  
Miete 380.- € inkl. Nebenkosten  

2-Zimmer-Wohnung zu vermieten  
55 Quadratmeter, Balkon, Küche und Bad.  
Miete 450.- € + Nebenkosten  



Das ist Bruno. Bruno wohnt genau *wie* Otto und Vanilla in Glückstadt. 
*Sein Haus* liegt *neben* Ottos Haus. Er ist geschieden, aber er wohnt nicht allein. *In dem Haus* wohnt auch *seine* neue Partnerin Mia. Mia hat zwei Kinder. *Ihre Tochter* heißt Sandra und ist 8 Jahre alt und *ihr Sohn* heißt Mark und ist 4 Jahre alt. Sandra und *ihr Bruder* wohnen *im ersten Stock*. Bruno liebt besonders *sein Arbeitszimmer* *im Erdgeschoss*. Dort steht *sein Computer*. Er surft gern im Internet und spielt gern Computerspiele. *Seine Partnerin* ist gern im Garten. Sie findet Computerspiele langweilig. Aber sie liebt *ihren Garten* und *ihre Blumen*.


das Haus  
sein Haus  
in dem Haus  


der Partner | die Partnerin  
seine Partnerin  


die Tochter  
ihre Tochter  

der Sohn  
ihr Sohn  

der Bruder  
ihr Bruder  

im ersten Stock  

sein Arbeitszimmer  

der Garten  
ihren Garten  

die Blumen  
ihre Blumen  



TRAUMWOHNUNG  

Traum  

Wohnung  

Meine Traumwohnung  


Ich lerne Deutsch -->  Ich bin *in einer Sprachenschule*.  

Ich bin shoppen -->	*in einem Laden*    

Ich suche Bücher, aber ich kaufe sie nicht --> *in einer Bibliothek*    

Ich bin in einem Haus. Es ist sehr groß. Ich wohne hier nicht. Ich bin im Urlaub und sehe mir das Haus an --> *in einem Schloss*  

Ich gehe spazieren. Hier sind Bäume, aber ich bin nicht im Wald. Ich bin in einer Stadt. --> *in einem Park*  

Ich bin in der Stadtmitte. An Donnerstag gibt es hier immer Obst und Gemüse. --> *auf einem Markt*

Ich bin in einer Kirche und habe einen Blick auf die Stadt von oben. --> *auf einem Turm*  

Das Wetter ist schön und ich schwimme. Ich bin im Wasser, aber nicht im Meer. --> *in einem Fluss*







---

## 14

https://hueber.de/shared/uebungen/menschen/kb/a1/livebook/l14/index.php


Schlafzimmer  
Kinderzimmer  
Arbeitszimmer  
Bad  
erster Stock  
Arbeitszimmer  
Erdgeschoss  
Küche  
Wohnzimmer  
Flur  
Toilette  
Schlafzimmer    
Kinderzimmer  
Bad  

Wohngemeinschaft





**Genetiv :** Name + s

Das ist der Ball von Frank.  
Das ist Franks Ball.  

*Name'* (bei s, ss, ß, z, c, x)  
Andreas' Vater  
Aziz' Ball  
Hans' Vater

Der Ball von Deniz -> Deniz' Ball  
Die Mutter von Lena -> Lenas Mutter


| **♂** | **Nominativ** | **Akkusativ** | 
| --- | --- | --- |
| *der* | Das ist sein Ball. | Er mag sein*en* Ball. |
| das | Das ist sein Auto. | Er mag sein Auto. |
| *die* | Das ist seine Flasche. | Er mag sein*e* Flasche. |
| *die (Pl.)* | Das sind seine Flaschen. | Er mag sein*e* Flaschen |


Ich mag Franks Ball. Ich mag seinen Ball.  

das Haus

Wie findest du Ottos Haus?  
Das Haus von Otto finde ich schön.  
Sein Haus finde ich schön.  

der Garten

Ich finde den Garten von Otto schön.  
Ich finde seinen Garten schön.  

die Küche  

Ich finde die Küche von Otto schön.  
Ich finde seine Küche schön.  


die Telefonnummer  

Wie ist seine Telefonnummer?  
Wie ist ihre Telefonnummer?  
Formell Frage: Wie ist Ihre Telefonnummer?  




| **♀** | **Nominativ** | **Akkusativ** | 
| --- | --- | --- |
| *der* | Das ist ihr Schuh. | Sie mag ihr*en* Schuh. |
| das | Das ist ihr Kleid. | Sie mag ihr Kleid. |
| *die* | Das ist ihre Flasche. | Sie mag ihr*e* Flasche. |
| *die (Pl.)* | Das sind ihre Shuhe. | Sie mag ihr*e* Schuhe. |



Hoch X Tiet (High X Low)  




die Miete (rent)  
die Warmmiete | die Warmmieten | miete mit Nebenkosten (rent with water, electricity, ... )  
die Kaltmiete | die Kaltmieten  


der Balkon -> einen Balkon  

Hat die Wohnung einen Balkon?  

Wie viele Zimmer hat die Wohnung?  
Wie groß ist die Wohnung?  
Wie groß ist deine Wohnung?  
Wie goß ist Ihre Wohnung?  

3 Zimmer, Küche, Bad  
Meine Wohnung ist 100 m^2^ groß. quadratmeter

umziehen + sein | umgezogen  (to move)  
Ich bin umgezogen.  

Wie hoch ist die Miete?  
Wie viel kostet die Miete?  

die Miete | die Mieten (kira)  
mieten (kiralamak)  
der Mieter (kiracı)  
die Mieterin (kiracı)  

vermieten (kiraya vermek)  
der Vermieter  (ev sahibi)  
die Vermieterin  (ev sahibesi)  

bezahlen (to pay)  

die Zeitung | die Zeitungen  
die Anzeige | die Anzeigen (ilan)  



---

## 15

https://hueber.de/shared/uebungen/menschen/kb/a1/livebook/l15/index.php


Hallbergmass bei München  
Das ist Darf (village)  
aud dem Land lieben (köye yaşıyor)  
in der Stadt leben  

Was sehen Sie aus Ihrem Fenster?  

die Moschee | die Moscheen  
der Pool  

Lesen Sie Blogs?  
Welche Blogger kennen Sie?  


**Wo + Dativ**  (Nere?)  
**Wohin + Akkusativ**  (Nereye?)  

Ich fliege ins Ausland / nach Deutschalnd / in die Türkei / in den  


es gigt + Akkusativ  
Es gibt drei Bücher hier.  

wenig X viel (az X çok)   

denken glauben meinen (think)

Ich denke ...  
Ich glaube ...  
Ich meine ...  
Vielleicht (perhaps) ...   



Kellner fragt: Zusammen oder getrennt? (hesap birlikte mi ayrı mı)  

lieben + Akkusativ  
Ich liebe dich.  

gehören + personal pronomen dativ  
meine possessive pronomen  

Die Tasche gehört mir = Das ist meine Tasche  

gefallen + Dativ  
gehören + Dativ  

Die Tasche gefällt mir = Ich finde die Tasche schön  

helfen + personal pronomen dativ  
danken + personal pronomen dativ  

Ich helfe dir.  
Ich danke dir.  
Ich glaube dir.  


Die Tasche gehört mir. (ich -> mir)  
Die Tasche gehört dir. (du -> dir)  

Die Tasche gehört dem Mann.  
Die Tasche gehört ihm. (er -> ihm)  

Die Tasche gehört dem Kind.  
Die Tasche gehört ihm. (es -> ihm)  

wir -> uns  
ihr -> euch  
sie/Sie -> ihnen/Ihnen  

auf (üstü açık alanlarda in yerine auf kullanılır)  
auf dem Markt  
auf dem Tür  


Du gefällst mir.  
Du gehörst mir.  



**Personalpronomen im Dativ**

- Hallo Maria und Pedro, wie geht es *euch*?  
- Danke, gut.  

- Maria, kommst du ?  
- Ja, Pedro, ich komme gleich und helfe *dir*  

- Wir haben Probleme mit den Hausaufgaben. Kannst du *uns* helfen?  
- Ja, klar.  

- Sind das *deine* Bücher? 
- Nein, die gehören nicht *mir*. Sie gehören Maria.

- Was machst du?   
- Ich schreibe eine Postkarte an Sandra und danke *ihr* für die Einladung.  

- Hast du am Sonntag Zeit?  
- Nein, Peter und Anja ziehen um und ich helfe *ihnen*  





Lesen Sie Blog. Sind die Sätze richtig oder falsch?  

Hamburg - das Tor zur Welt  

Meine Lieblingsstadt ist Hamburg. Ich bin oft dort und besuche Freunde. Die Stadt hat 1.8 Millionen Einwohner und liegt in Norddeutschland an der Elbe. In Hamburg gibt es alles: Kunst und Kultur, Restaurants und Bars, Läden und Geschäfte - und viel Wasser. Ihr wollt Hamburg besuchen? Das müsst ihr sehen.  

Hamburg am Wasser  

Besonders spanned sind der Hafen mit den Container-Schiffen aus der ganzen Welt und die Speicherstadt. Dort lagern Waren von den Schiffen: Kaffee, Tee, Gewürze, Kakao, elektronische Produkte, Teppiche und vieles mehr. Aber es gibt auch Museen, Ausstellungen, Lesungen und Theateraufführungen.  

Hamburg von oben  

Die Kirche St. Michaelis (die Hamburger nennen sie "Michel") ist das Wahrzeichen von Hamburg. Der Blick vom Kirchenturm (132 Meter hoch!) auf die Stadt und den Hafen ist einfach toll!  

Hamburg am Abend  

Natürlich gibt es in Hamburg überall viele Kneipen. Besonders gern mag ich aber die Atmosphäre am Großneumarkt, das ist ein Platz in der Hamburger Neustadt mit Kneipen, Cafes und Restaurants. Vielleicht sehen wir uns irgendwann mal?  

Ewa aus Krakau  

Danke für die Tipps, Jan! Dein Blog gefällt mir gut. Hamburg kenne ich noch nicht, aber jetzt möchte ich unbedingt hin und den Hafen sehen.    



Einwohner | Wappen | alt | 500 | Bern | spricht | Hauptstadt | Berlin  
Martin lebt in Bern  
Bern hat 130.000 Einwohner und ist die Hauptstadt der Schweiz.  
In Bern spricht man Berner Deutsch.  
Der Zytglogge, das ist der Zeitglockenturm, ist sehr alt. Die Uhr ist 500 Jahre alt.  
Bern und Berlin haben etwas gemeinsam. Beide Wappen haben einen Bären.  



---

## 16

https://hueber.de/shared/uebungen/menschen/kb/a1/livebook/l16/index.php


Hilfe rufen  
warten  

die Angst | die ängste    
Angst haben  

genervt sein  


nichts tun (hiçbirşey yapmadan beklemek)  
Sie tunnst nicht.  

warten  
Hilfe rufen

die Aufzugfirma | die Aufzugfirmen  

der Techniker | die Technikerin  

reparieren


der Kopf | die Köpfe  
das Feld | die Felder  (field)  

Wie geht's dir / Ihnen ?  
Mir geht's gut.
Uns geht's gut.  

Wem gehört die Uhr?  
Die Uhr gehört ihm.

Wem gehören die Bücher?  
Die Bücher gehören ihm. 



**einen Termin vereinbaren**

Passt es Ihnen heute Nachmittag um 16 Uhr?  
Ich habe einen anderen Termin um 11 Uhr.
Kann ich um 14 Uhr kommen?  

**den Termin verschieben**  
ich verschiebe den Termin von Freitag auf Deinstag.  

Ich habe einen Termin um 11 Uhr. Ich kann aber leider nicht kommen.  

**einen Termin absagen** (cancel)
Ich sage den Termin ab.  



**Wo + in Dativ**  

*der*: Ich komme in ein*em* Monat zurück.  
*das*: Ich komme in ein*em* Jahr zurück.  
*die*: Ich komme in ein*er* Stunde zurück.  
*Pl.*: Ich komme in zwei Wochen zurück.


- Wann kommst du zurück?  
In einem Monat.  


**vor X nach** (before X after)  

Wann kommt er?  

*der*: Er kommt vor *dem* Kurs.  
*das*: Er kommt nach *dem* Essen.  
*die*: Er kommt nach *der* Uni.  
*Pl.*: Er kommt vor *den* Hausaufgaben.  


(Für) Wie lange kommen Sie?  
(Für) Wie lange bleiben Sie?  
Ich komme für einen Monat.  
Ich bleibe für einen Monat.  

bleiben (stay)  



Tut mir leid, der Bus ist nicht gekommen.  
Entschuldigung, ich habe zu lang geschlafen.  
Tut mir leid, ich war in einer anderen straße.  
Ich habe keine Taxi gefunden.  
Ich war gestern krank.  

Ich glaube ihm.  

Hast du am Sonntag zeit?  
Ja, ich habe zeit.  (vereinbaren)
Nein, ich habe keine zeit.  

Ich kann doch nicht (absagen).  


**sein | gewewsen**  

Bist du in Köln gewesen -> *Warst du .... in Köln?*


in Wann + Dativ  
nach - vor Wann + Dativ  
(für) wie lange + Akkusativ  

ab Wann? Abwann?  

Abwann ist die Party?  
Wann ist die Party?  

um wie viel uhr?  (Wann)  
am Wann?  

von .. bis  Von wann bis wann? Wann?


anfangen | angefangen  (to begin)  

Der Deutschkurs hat von einer Woche angefangen.  

Wann gehen Sie einkaufen?  
Ich gehe nach dem Kurs einkaufen.  


"Das war eine schwere Geburt" (çok zor bir iş için kullanılan deyim)    
"Ich verstehe nur Bahnof" (hiç bir şey anlamadım anlamında deyim)  




**ZEITPRÄPOSITIONEN**

Lesen Sie die Sätze.  
"Vor" ist eine Präposition für vergangene Ereignisse, (vergangene Ereignisse: past event)    
"für" ist eine Präposition für die Dauer, (Dauer: period)    
"in" ist für die zukünftige Ereignisse und (zukünftige: future)    
"nach" für schon abgeschlossene Ereignisse. (abgeschlossene: terminated)  



Peter möchte *für* ein Jahr nach Japan gehen.  
Er hat *vor* einem Jahr schon ein Praktikum in Japan gemacht.  
Anne möchte *nach* ihrem Medizinstudium in Afrika als Ärztin arbeiten.  
Barbara beginnt *in* drei Monaten mit dem Studium.  
Moritz hat *vor* einem halben Jahr mit seinem Ingenieur-Studium angefangen.  
*In* vier Jahren ist er fertig. Dann möchte er gern in einer Autofirma arbeiten.  
Maria möchte *nach* dem Deutschkurs die Prüfung machen.  



Was kann ich für Sie tun?

*Nach* der Schule hat er Elektroinstallateur gelernt.  
Seit 16 arbeitet Herr Brunner als Hausmeister bei der Firma.  
Er kümmert sich um die Heizung, das Wasser und den Strom.  
Er repariert Fenster und Türen. Außerdem schneidet er Bäume, Büsche und Hecken. 
*Von* Montag *bis* Freitag arbeitet er immer *von* 8.00 *bis* 16 Uhr.
Er hat Mittagspause *von* 12.00 *bis* 12.30 Uhr.  
Die Arbeit macht *ihm* Spaß.



**TERMIN**

*Termine verschieben*

- Ich kann leider doch nicht ins Kino gehen/ kommen.   
- Können wir den Termin verschieben?  
- Ich möchte den Termin verschieben.  


*Pläne beschreiben*

- Vor/ Nach dem Deutschkurs/ der Uni ...  
- Ab Samstag bin ich für 2 Wochen im Urlaub.  
- Am Montag bin ich aus dem Urlaub zurück.  
- Von Freitag bis Dienstag bin ich in Berlin.  



*Alternativen vorschlagen*

- Ich kann am Freitag.  
- Am Sonntag habe ich Zeit.  
- Passt es Dir am Sonntag?  
- Wollen wir am Freitag ins Kino gehen?  


*Ihre Tandem-Partnerin schreibt Ihnen folgende Mail und möchte einen Termin vereinbaren.*   

Lieber/ Liebe ....   
wollen wir uns diese Woche endlich mal treffen? Ich habe aber leider ein volles Programm. Von Montag bis Freitag bin ich auf einer Tagung in Berlin. Am Donnerstag Vormittag gehe ich zur Uni und am Abend habe einen Spanischkurs. Am Samstag Nachmittag besuche ich meine Großeltern und ab Sonntag fahre ich für eine Woche in Urlaub auf Sylt. Am Freitag habe ich aber den ganzen Tag frei. Treffen wir uns im Cafe "Luxus" um fünf? Hast du da Zeit?  
Ich freue mich schon auf Freitag.   
Liebe Grüße  



---

## 17

https://hueber.de/shared/uebungen/menschen/kb/a1/livebook/l17/index.php


*in + Dativ*  
Wann ist die Pause?  
in 5 minuten  
in einer Stunde  
in einem Tag  
in einem Jahr  


**mit + Dativ**

Fabian geht mit dem Hut in die Prüfung.  
Fabian geht mit der Gitarre in die Prüfung.  
Fabian geht mit dem Kursbuch in die Prüfung.  
Fabian geht mit den Blumen in die Prüfung.  


der -> dem  mein -> meinem  
die -> der  mein -> meiner  

seinem Hut  
seiner Gitarre  
seinem Kursbuch  
seinen Blumen  
meinen Blumen  
ihren Blumen  




**ohne + Akkusativ**

der -> den  mein -> meinen  

Cherry geht ohne den Hut / meinen Hut in die Prüfung.  
die Gitarre / meine Gitarre  
das Kursbuch / mein Kursbuch  
die Blume / meine Blumen  


Was nehmen Sie in den Urlaub mit?  
Ich fahre mit meinem / dem Handy in den Urlaub.  
Ich fahre ohne meinen / den Wecker in den Urlaub.  


Fabian will lieder macher werden.  
Ich möchte ... (Beruf) weden.  

Ich will ein Auto kaufen.  
Ich will durch Europa reisen.  


BEWERBUNG (application)

anmelden (register)  
lesen  
bekommen

schaffen (accomplsih)

abschließen (finish, complete)

beginnen

finden
aufnehmen

bestehen

werden  



Im Sommer hat Sofie ihre Ausbildung als Friseurin abgeschlossen.  
Sie hatte große Angst vor der Prüfung.  
Aber zum Glück hat sie die Prüfung geschafft.  
Jetzt möchte sie endlich Geld verdienen.  
Dann möchte sie mit ihrem Freund Johnny ein Motorrad kaufen und durch Europa fahren.  
Zuerst macht sie aber noch den Führerschein.  
Sie möchten durch viele Länder reisen, die Welt und andere junge Leute kennenlernen.  
In ein paar Jahren möchten sie und Johnny heiraten und Kinder haben.  



*WÜNSCHE UND PLÄNE*

Welche Wünsche hast du?

Welche Wünsche haben die Leute?

Ich will ...  

auf keinen Fall dick werden.  
bald heiraten.  
endlich wieder ohne Krücken gehen.  
Karriere machen.  
ein Fest nur für Frauen machen.  
nicht wie meine Mutter werden.  
Musik studieren.   
wenig arbeiten und viel Geld verdienen.  
mit dem Zug durch Europa fahren.  
Model werden.  
reich werden.  
Tierärztin werden.  
Pause machen.  


*WOLLEN UND KÖNNEN*


Cherry *will* unbedingt Sängerin werden.  

Sara und Felix *wollen* auf keinen Fall heiraten.

Nächstes Jahr *will* ich meine Ausbildung abschließen.

Wir *wollen* unbedingt die Führerscheinprüfung schaffen.

Dann *können* wir mit dem Motorrad durch Europa reisen.

Vielleicht *will* Jan Liedermacher werden.




---

## 18

https://hueber.de/shared/uebungen/menschen/kb/a1/livebook/l18/index.php

die Krankheit | die Krankheiten | hastalık    
die Gesundheit | sağlık  
die Fähigkeit | die Fähigkeiten | ability  

das Thermometer | die Thermometer  
die Hand | die Hände  

husten  

wehtun | Schmerzen haben

ich tue weh  
du tust weh  
er tut weh  

wehgetan (PII)  

bleiben  (stay)  


nicht mehr: Ich habe medikamente genommen und jetzt geht es mir gut. Das fieber ist weg, also es ist nicht mehr da.  

immer noch: Ich habe seit zwei Tagen Fieber und jetzt auch. Es ist nicht weg. Ich habe Medikamante genommen aber es ist immer noch da.

die Ambulanz  
die Notaufnahme | emergency  
Arzt  
Hausarzt  

Geben X Nemen

Geben Sie ihm diesen Tee! -> Befahl, Empfehlung, Ausrufezeichen

Geben Sie ihm diesen Tee? -> Ja, Nein Frage, Fragezeichen

Trinken Sie viel wassar bitte!

Trinken Sie Tee?

Gehen Sie zum Arzt!

Gehen Sie zum Arzt?





Geben Sie ihm doch diesen Tee!

Schwester  
die Nonne | die Nonnen
das Kraut | die Kräuter | herbal    
die Blumen  
der Korb | die Körbe

das Kloster | die Klöster | manastır  
Klosterladen  

Sie trägt die Körbe.

Die Nonne liebt in das Kloster  
Kommen Sie mit  

krank X gesund (seid)  
Ich bin krank. Ich bin gesund.  

Kopfscmerzen haber

Ich gehe zum Arzt.  

Schmerzen geschrieben:  
Mein Kopf tut weh  

Ratshläge geben:  
Welche Ratshläge gibt Schwester Angelika den Leuten?  
Imperativ  
Bleiben Sie doch im Bett!  
Geben Sie ihm doch diesem Tee!  
Trinken Sie (doch) viel Tee!  
Gehen Sie (doch) zum Arzt!

Was hat Schwester Angelika gesagt?  

Sie sagt, du sollst im Bett bleiben.  
Sie sagt, du sollst diesen Tee trinken.  
Sie sagt, ich soll viel Tee trinken.  
Sie sagt, ich zum Arzt gehen.  


über Krankheiten sprechen:  
Gegen Bauchschmerzen trinke ich ...  

sollen -> Modalverb | should

Ich soll dir diesen Tee geben.

Du sollst diesen Tee trinken.  

sollen
soll
sollst
soll
sollen
sollt
sollen


der Ratschlag | die Ratschläge | advice, suggestion

der Ratgeber | die Ratgeber | advisor  
die Ratgeberin | die Ratgeberinnen | advisor

Wortfeld

Körperteile  

Gehen Sie zum Arzt!




der Doktor  | die Doktoren  
der Arzt  | die ärzte  
die Apotheke  |  die Apotheken  
das Medikament | die Medikamente  
das Rezept  | die Rezepte  | ein Rezept verschieben  
die Praxis  | die Praxen  
der Husten  | die Husten | Husten haben
das Fieber  | die Fieber  
der Schnupfen | die Snupfen | Meine nose löft  
der Schmarz | die Schmerzen  
die Tablette  | die Tabletten   
die Salbe  | die Salben  
das Pflaster  | die Pflaster  

der Arm | die Arme  | arm  
das Bein | die Beine  | leg  

Er hat keine Schmerzen in den Armen und Beinen   
Das Fieber ist nicht sehr hoch.  
Er hustet gar nicht.  
Er hustet sehr viel.  
Mein Kopf tut immer noch weh.  
Mein Kopf tut nicht mehr weh.  
Das Fieber ist immer noch hoch.  
Das Fieber ist nicht mehr hoch.  

bleiben  
bleiben im Bett  


das Skelett | die Skelette  
das Teil | die Teile  
der Körper | die Körper  

der Kopf | Head    
der Hals  | Throat  
der Rücken  | Back  
die Brust  |  Chest  
der Bauch  | Stomach  
der Arm    
die Hand    
der Finger
das Bein  | Leg
der Fuß  
das Knie  
das Ohr  | Ear  
das Auge  | Eye  
der Zahn  | Tooth | Zahnarzt
die Nase  
der Mund  | Mouth  


Rund um die Gesundheit  

*Telefongespräch*

- Hallo Lea, ich kann heute leider nicht zum Schwimmen kommen. Ich muss absagen.  
- Warum denn?  
- Ich bin krank  
- Oh, was hast du denn?  
- Ich habe Kopfschmerzen und ich huste  
- Oh, das tut mir leid. Hast du auch Fieber ?  
- Ja, es ist nicht sehr hoch. Aber gut geht es mir nicht. Und meine Arme und Beine tun mir auch weh  
- Ach Mensch! Wie schade!  
- Ja, das finde ich auch. Also ich bleibe im Bett.  



*Ratschläge* (advice)  

Ihr Nachbar arbeitet ein halbes Jahr nicht. Geben Sie ihm Ratschläge mit "doch".
Ä, ö, ü können Sie auch ae, oe, ue schreiben.

 
durch Europa reisen -> Reisen Sie doch durch Europa!   
ins Ausland gehen -> Gehen Sie doch ins Ausland!  
ein Instrument lernen -> Lernen Sie doch ein Instrument!  
den Motorradführerschein machen -> Machen Sie doch den Motorradführerschein!  
noch eine Fremdsprache lernen -> Lernen Sie doch noch eine Fremdsprache!  



*Wie essen wir gesund?*

Der Ernährungswissenschaftler T. Lohmann sagt: "Essen Sie, was Sie wollen." Sie haben viel zum Thema Essen gelernt und gelesen? Vergessen Sie es! Es ist nicht wichtig. Es gibt keine gesunden und auch keine ungesunden Lebensmittel. Wir sollen fünfmal am Tag Obst und Gemüse essen? "Nicht unbedingt", sagt T. Lohmann. Möchten Sie Obst und Gemüse essen und schmeckt es Ihnen? Schön, dann essen Sie es. Sie möchten eigentlich gerade gar kein Obst und Gemüse essen? Dann sollen Sie es auch nicht tun.   
Und wie essen wir dann gesund?  
T. Lohmanns Ratschlag lautet: "Ihr Körper weiß es." Sie frühstücken immer morgens um 7.00 Uhr? Das sollen Sie nicht tun. Essen Sie nicht zu festen Zeiten! Fragen Sie immer Ihren Körper: habe ich gerade Hunger?  
Und was sollen wir essen?" Auch das ist ganz leicht. Fragen Sie sich: "Was möchte ich gerade gern essen?" Unser Körper braucht viele verschiedene Nahrungsmittel und kann uns immer sagen, was gut für ihn ist.  


Gehen : yayalar için  gehen links  
Fahren: araçlar için  fahren links  

an die ...straße

die zahnpasta | diş macunu  

Was tut dir weh?  
Was tut Ihnen weh?  
Mein Kompf tut weh. | Ich habe Kopfschmerzen. | Mir tut der kompf weh.  

Was fehlt dir?  
Was fehlen Ihnen?  


der Witze:  
Meine nose läuft.  
Dann halt sie doch fest.  (fest halten)  

das Heilkraut | die Heilkräuter  
die Naturmedizin  

glauben an Gott  
glauben an Naturmedizin  
Ich glaube (nicht) an Naturmedizin.  


die Erkältung  
die Grippe  
die Warmflasche | sıcak su torbası  

Ich gehe warmduschen. | Ich dusche warm. | Ich nehme eine warm dusche.  

[Warmduscher](https://dict.leo.org/german-english/Warmduscher) | looser
Mimose 


Schau mal, hier sind die Fotos von früher:
Da war mein Bruder, ich war
sechs und meine Schwester
war zehn Jahre alt. Ich 
hatte schon ein Fahrrad und 
war sehr glücklich mit meinem Rad! Mein Bruder und ich 
waren immer fröhlich und wir zwei 
hatten immer viel Spaß. Aber meine große Schwester 
war immer nur mit ihren Freundinnen zusammen. Die 
waren nicht so sympathisch und haben nie mit uns gespielt.


Warum hast du dich bei Simon nicht entschuldigt?  
Haben Sie die E-Mail von Professor Klüger schon bekommen?  
Wie hat Ihnen das Konzert gefallen?  
War das Essen wirklich schlecht? Hast du dich beschwert?  
Ich muss noch einmal ins Büro gehen. Ich habe mein Handy vergessen.  
Das Auto hat mir früher gehört.   



---

## 19

https://hueber.de/shared/uebungen/menschen/kb/a1/livebook/l19/index.php


über etwas sprechen  

über etwas / Thema / Nachbarin / das Buch / das Bild / Leute sprechen  

So war Walter früher.

sein + adj

1990 -> Er war dick. Er hatte keine Bart. Er hatte kurze haare. Er war klein.  
2018 -> Er is dünn. Er hat eine Bart.  


das Harr | die Harre  



Ich bin gegangen.  
Ich bin gelesen.  
Ich war. | Ich bin gewesen.  
Ich hatte. | Ich habe gehabt.  

aussehen (trenbare verb)  
Sie sieht hübsh aus.  
Wie sieht er aus?  
Wie finden Sie er?  

das Aussehen | outlook  


Nicht trenbare verben:  
be-  
ver-  
er-  
ent-  
miss-  
zer-  
emp-  
ge-  





verlieren | verloren  (to lose)  
wehtun | wehgetan (to hurt)  

Mein Arm hat mir wehgetan.  






*Präteritum von haben und sein*

Schau mal, hier sind die Fotos von früher: Da *war* mein Bruder 4, ich *war* sechs und meine Schwester *war* zehn Jahre alt. Ich *hatte* schon ein Fahrrad und *war* sehr glücklich mit meinem Rad! Mein Bruder und ich *waren* immer fröhlich und wir zwei *hatten* immer viel Spaß. Aber meine große Schwester *war* immer nur mit ihren Freundinnen zusammen. Die *waren* nicht so sympathisch und haben nie mit uns gespielt 


*Perfekt von nicht trennbaren Verben*


sich entschuldigen - gehören - gefallen - beschweren - vergessen - bekommen  


Warum hast du dich bei Simon nicht entschuldigt?  
Haben Sie die E-Mail von Professor Klüger schon bekommen?  
Wie hat Ihnen das Konzert gefallen?  
War das Essen wirklich schlecht? Hast du dich beschwert?  
Ich muss noch einmal ins Büro gehen. Ich habe mein Handy vergessen.  
Das Auto hat mir früher gehört.  










---

## 20

https://hueber.de/shared/uebungen/menschen/kb/a1/livebook/l20/index.php



**runter X auf** (down X up)

runterfallen  
runtergehen X raufgehen  
runtersehen X raufsehen  

Komm soft runter!  


**raus X rein** (out X in)  

rausbringen X reinbringen   

Putzfrau  



**Informel Imperativ**


Du deckts den Tisch -> Deck den Tisch!  

Ihr deckt den Tisch -> Deckt den Tisch!  

Du machst das Bett -> Mach das Bett! Mach bitte das Bett!  

Ihr macht das Bett -> Macht das Bett! Macht bitte das Bett!  


| **Du**                                                | **Ihr**                                   | 
| ---                                                   | ---                                       | 
| Schlaf!                                               | Schlaft!                                  |
| Du schläfst viel -> Schlaf nicht zu/so viel           | Ihr schlaft viel -> Schlaft nicht viel    | 
| Du räumst aus -> Räum aus                             | Ihr räumt aus -> Räumt aus                | 
| Sei!                                                  | Seid!                                     |
| Du bist fleißig -> Sei fleißig                        | Ihr seid fleißig -> Seid Fleißig          | 
| Hab!                                                  | Habt!                                     | 
| Hab keine angst                                       | Habt keine angst                          |
|                                                       | Seid leise bitte                          |
|                                                       | Seid loud bitte                           |






**Drei Imperativ**  
Du  | Ihr  | Sie  



| **decken**            | **Imperativ**     |  
| ---                   | ---               |
| ~~decke~~             |                   |
| ~~Du~~ deck~~st~~     |      Deck!        |
| ~~deck~~              |                   |
| ~~decken~~            |                   |
| ~~Ihr~~ deckt         |   Deckt!          |
| Sie decken            | Decken Sie bitte! |


Du deckts den Tisch -> Deck den Tisch  
Ihr deckt den Tisch -> Deckt den Tisch  
Sie decken den Tisch -> Decken Sie bitte den Tisch (formel)  


**schlafen (vokal wechsel a -> ä) -> du schläfst (ä -> a) -> schlaf**   

du schläfst -> schlaf


fahren -> du fährst -> fahr  

sprechen -> du scprichst > sprich  

lesen -> du liest -> lies  
lesen -> ihr lest -> lest  

essen -> Sie essen -> Essen Sie!  
essen -> ihr esst -> Esst!  
essen -> Du isst -> Iss!  

ausräumen -> du räumst aus -> Räum aus!  
schlafen -> Du schläfst -> Schlaf!  
vergessen -> vergisst -> vergiss  

still sein = leise  
aufpassen -> Pass auf!  
aufpassen -> Passt auf!

Geduld haben (patience)  



**treffen + Wen akkusativ**  

Ich habe meinen Vater getroffen.  
Ich habe meine Mutter getroffen.  
Ich habe einen Freund getroffen.  

Ich treffe ein Freund.  
Ich habe Ali getroffen.  



Alex putzt das Bad.  
Er putzt es.  

Subj + Verb + Akk Obj  

Sara ruft Peter an.  
Sie ruft ihn an.  


Vergiss es.  

günstig / billig X teuer  
freiwillig X unfreiwillig  




*Was sollen Carla und Tim im Haushalt machen?*  

Tim, *reparier* bitte Carlas Fahrrad!  
*Bring* den Abfall *raus*.  
Carla, *räum* bitte unbedingt dein Zimmer *auf*  
*Wasch* bitte die Wäsche!  
Tim und Carla, *Putzt* bitte die Fenster in der Küche!  
*Geht* zusammen einkaufen! Und *schickt* mir mal eine E-Mail.  
Ich vermisse euch schon jetzt!   
Eure Mama  

| Imperativ     | du            | ihr           |
| ---           | ---           | ---           |
| gehen         | Geh           | Geht          |
| schicken      | Schick        | Schickt       |
| reparieren    | reparier      | repariert     |
| rausbringen   | bring raus    | bringt raus   |
| putzen        | putz          | putzt         |
| aufräumen     | räum auf      | räumt auf     |
| waschen       | wasch         | wascht        |


**Personalpronomen im Akkusativ**

- *Die Tür* ist auf. Kannst du *sie* bitte zumachen?  
- Ja gerne.  

- Susanne und Peter, habt *ihr* am Samstag Zeit? Ich möchte *euch* zum Essen einladen.  

- Wo ist *Dominik*? Ich habe *ihn* nicht gesehen.  
- *Er* ist bei Max.  

- Wann kommt *ihr*?
- Um 13.34 Uhr.Kannst du *uns* bitte abholen?  

- Die Verbindung ist so schlecht, *Daniel*. Ich kann *dich* nicht hören.  

- *Deine Eltern* haben angerufen.
- Wirklich? Ich rufe *sie* gleich zurück.  



**Personalpronomen**


| *Nominativ*   | *Akkusativ*   |
| ---           | ---           |
| Ich           | mich          |
| du            | dich          |
| er            | ihn           |
| sie           | sie           |
| es            | es            |
| wir           | uns           |
| ihr           | euch          |
| sie / Sie     | sie / Sie     |



Hallo .....,  
dein Angebot finde ich toll. Ich heiße Gert, bin 27 Jahre alt und studiere Architektur. Und ich bin (nicht/sehr) ordentlich und putze (oft/selten) und (gründlich/ oberflächlich). Ich koche wahnsinnig gern. Dein perfekter Mitbewohner also!   
Ich freue mich schon auf Deine Antwort.  
Liebe Grüße  



Liebe ...,  
deine Wohnung ist im Zentrum und sieht sehr gut. Das Zimmer gefällt mir.  
Ich heiße Serdar und bin 38 Jahre alt. Für sechs Monate in Ankara möchte Ich ein Ausbildung machen.  
Ich kann nicht kochen gut aber ich kann die Spülmaschine ein und ausräumen. Ich putze die Küche gern, ich staubsauge und wische den Boden.  
Ich bin sehr ordentlich und leise.  
Ich freue mich schon auf Deine Antwort.  
Viele Grüße






---

**Hab keine angst!**

<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script><blockquote class="twitter-tweet" data-lang="en"><p lang="tr" dir="ltr">Michael Ende&#39;nin ölüm yıl dönümü bugün (1995).<br>&quot;Bitmeyecek Öykü&quot; ve &quot;Momo&quot; gibi harikulade romanlar yazdı. <br><br>Mezarı oldukça dikkat çekici. Kaplumbağa şeklindeki mezar taşı detayında şu yazıyor: &quot;Kaygılanmana gerek yok&quot;. <a href="https://t.co/sqphISXz5j">pic.twitter.com/sqphISXz5j</a></p>&mdash; Kaan H. Ökten (@Kaan_H_Okten) <a href="https://twitter.com/Kaan_H_Okten/status/1034298339959955456?ref_src=twsrc%5Etfw">August 28, 2018</a></blockquote>


---









---

## 21

https://hueber.de/shared/uebungen/menschen/kb/a1/livebook/l21/index.php


**erlaubt X verbaten** (izinli X yasak)


hupen (korna)


der Fußgänger | die Fußganger  
der Fahrradfahren | die Fahrradfahren  
der Straßenverkehr | die Straßenverkehr  
die Ampel | die Ampeln  
der Bürgersteig | die Bürgersteig  

zu Fuß gehen  

Als Autofahrer fahre ich immer bei Grün über die Ampel.  
Zu Fuß gehe immer / nie bei Rot über die Ampel.  

Mit dem Auto fahre ich ...   
Mit dem Fahrrad fahre ich nie bei Rot über die Ampel.  


Bei grün in Ampel gehen ist erlaubt.  

Die Kinder hier spielt an der Straße.  
Die Kinder darf aber nicht neben der Straße spielen.  
Die Eltern muss auf Kinder achten.  

Die familie hier grillen.  
Man darf nicht grillen in den Park.  
Man darf im Pool nicht Wasser trinken.  


**Der Ampelmann**

ie Regeln für Ampeln sind einfach. Bei Rot müssen Sie stehen bleiben, bei Grün dürfen Sie gehen.  
Autofahrer und Fahrradfahrer müssen auf Ampeln achten - und natürlich auch auf Fußgänger.   
Die Ampeln für Fußgänger sehen aber besonders aus:  
Sie haben einen "Ampelmann". Dieser Ampelmann ist in Deutschland sehr bekannt. Es gibt ihn seit 1961, er ist also über 50 Jahre alt.    
Viele Länder haben einen Ampelmann. Sie sehen verschieden aus.  
Manchmal ist er dick oder dünn, manchmal schiebt er ein Fahrrad oder trägt einen Hut, und manchmal gibt es auch eine Ampelfrau.  


*Modelverben*

können - wollen - sollen - dürfen - müssen

Wir *müssen* früh aufstehen. Die Prüfung fängt schon um 7.00 Uhr an.  
Ich *kann* heute leider nicht kommen. *Können* wir den Termin verschieben?  
Sara *will* unbedingt ihren Führerschein machen, aber sie *darf* noch nicht. Sie ist erst 16.  
Du *musst* noch abwaschen. Heute Abend haben wir Gäste.  
Die Ärztin sagt, ich *soll* viel schlafen, aber ich *will* tanzen gehen.


- *Kannst* du Tennis spielen?  
- Ja, aber ich *darf* im Moment nicht spielen. Ich habe Probleme mit meinem Rücken.  

- *Willst* du heute mit mir Fußball spielen?  
- Nein, ich habe leider keine Zeit. Ich *muss* arbeiten.  

- Der Doktor sagt, du *sollst* viel trinken.   
- Ich habe aber keinen Durst.  

- *Darf* ich hier rauchen?  
- Nein, tut mir Leid. Das ist hier nicht erlaubt.  

- Ich *muss* heute noch Hausaufgaben machen. *Kannst* du mir helfen?   
- Ja, kein Problem.  
























---

## 22

https://hueber.de/shared/uebungen/menschen/kb/a1/livebook/l22/index.php


verrücht (crazy)  
bunt (colorful)  

Mottoparty ()


anhaben -> Was hat Fabian an?  
tragt   -> Was trägt Fabian?  

*anhaben + Akkusativ*   

*tragen + infinitiv*  


Er trägt eine Hose. Die Hose ist kurz.  

Was hat mädchen links neben / von ihm?  


Ich finde das T-shirt besser als ...  
Ich finde Alis briller besser als Velis (brille).  


Regel: genauso + Adjektiv + wie  
++  -> ++  
+   -> +

Janas Hose gefällt mir genauso gut wie ihre Bluse.  
Janas Hose (Nominativ) gefällt mir (Dativ) genauso gut wie ihre Bluse (Nominativ).  

Ich mag Pizza genauso gern wie Sphagetti.  


Regel: Komperativ + als  
++  -> +  


Ich finde Fabians Hase besser als sein Hemd.  
Ich mag Tee lieber als Kaffee.  

Wen + Akk


**gut gefallen**  
**gut finden**  
**gern mögen**  




Ich finde Harrys Kostüm besser als Fabians (Kostüm).  
Veras Kleid gefällt mir besser als Jasmins.  
Ich mag lila genauso gern wie rosa.  

| Ich | finde | Fabians Kostüm | gut. |
| --- | --- | --- | --- | 
| Subj Nominativ | Verb Pos 2 | Akk Obj | |


Fabians Kostüm gefällt mir.  
(Sub Nominativ Wer? + Verb + Dativ)  

Ich mag Fabians Kostüm.  
(Subj + Verb + Akk Obj)  



*Komparativ und Superlativ*  

Peters Haus ist *größer als* Kais Haus, aber *am größten* ist Pauls Haus.  
Peters Haus ist *kleiner als* Pauls Haus. Am *kleinsten* ist Kais Haus.  
Kais Haus ist *am ältesten*. Pauls Haus ist *am modernsten*.  
Pauls Haus kostet *viel*. *Am billigsten* ist Kais Haus.  
In Kais Garten gibt es *mehr* Bäume *als* in Pauls Garten. Kais Garten ist *viel schöner*  



Der Hut gefällt mir besser als die Mütze.    
Schau mal, die Bluse kostet genauso viel wie das T-Shirt.  
Die Jacke finde ich schöner als den Mantel.  
Die Hose finde ich nicht schön. Nimm doch die Jeans hier. Die finde ich viel besser als die Hose.  
Ich mag T-Shirts genauso gern wie Blusen.  



-nach s-, d- t-, ss- , ß-, sch-, s-, z-

-esten größten

Ist NY so groß wie Hongkong?

-Nein ,NY ist nicht so groß wie HK.

HK hat aber meher Einwohner als HK.

HK hat weniger Einwohner als NY.



dunkel-dunkler-am dunelsten

lang - länger - am längsten

gut - besser - am besten

hoch - höher - am höchsten

teuer - teurer-am teuersten

schnell-schneller-am schnellsten

viel-mehr-am meisten

gern-lieber-liebsten

---

## 23

https://hueber.de/shared/uebungen/menschen/kb/a1/livebook/l23/index.php





- Natascha und Ella singen und schreiben Lieder.   
- Sie würden gern eine CD machen.  
  
- Klaus hat kein Auto.	
- Aber er würde gern den Führerschein machen.  


- Meine Tochter fährt gern Motorrad.	
- Ich würde ihr gern ein Motorrad schenken.  


- Am Freitag spielt unsere Lieblingsband in Berlin und es gibt keine Tickets mehr.  
- Wie schade! Wir würden gern zum Konzert gehen.  


- Ich war noch nie in Deutschland.  
- Ich würde gern Berlin besuchen.  



*Zeitpräpositionen*

*Am* Mittwoch hat Isabella Prüfung. Wir treffen uns *um* 17.00 vor der Schule und wollen ihr gratulieren.

Frau Stern hat *am* 17. August Geburtstag. *Von* 15.00 Uhr *bis* 16.00 Uhr gibt es Kaffee und Kuchen in ihrem Büro.

*im* Juli hat Herr Bellmann Urlaub, *vom* 5. Juli *bis* zum 19. Juli 

*nach* dem Urlaub zieht er dann mit seiner Familie um.

*in* vier Wochen ist schon wieder Weihnachten. Und ich habe noch keine Geschenke.
 
*ab* Montag bin ich *für* drei Wochen im Urlaub.




Anrede – Liebe ... (weiblich)/ Lieber ... (männlich), Briefanfang – ich freue mich sehr auf die Einladung zum deiner Geburtstagsparty. Herzlichen Glückwunsch!, Brieftext  – Ich hätte hier eine Frage: Soll ich etwas mitbringen?, Briefschluss – Liebe/ Viele/ Herzliche Grüße, Unterschrift – Name des Absenders






Sie bekommen eine Einladung von Josh Weller aus dem Fachschaftsrat an Ihrer Universität.

Lesen Sie die Einladung und schreiben Sie eine Antwort.

Bielefeld, 15 Juni 2013

Liebe Studentinnen und Studenten ,

am 28. Juli wollen wir das Semesterende feiern.

Wie jedes Jahr wollen wir ein Picknick machen und natürlich viel Spaß haben. Dieses Jahr haben wir auch ein Programm vorbereitet. 

Wir freuen uns schon sehr!

Wir treffen uns um 10.00 Uhr am Hauptbahnhof und fahren mit Bussen an den Kalmbacher See. Macht ihr auch dieses Jahr mit? 
Bitte gebt uns bis zum 30. Juni Bescheid.

Viele Grüße

Josh Weller

Schreiben Sie einen Text von 50 Wörter zu den drei Punkten.

- Danken Sie für die Einladung.

- Sagen Sie: Sie kommen gern zum Fest.

- Fragen Sie: Sollen Sie etwas mitbringen?

Tipp: 
Sie möchten einen Brief schreiben. Was ist besonders wichtig?
- Vergessen Sie nicht das Datum, die Anrede und den Gruß.
- Überlegen Sie vor dem Schreiben: Kenne ich die Person gut? Soll ich "du" oder "Sie" sagen?
- Schreiben Sie zu jedem Punkt 1-2 Sätze.


Jahreszeiten


Ins Wasser gefallen ?

 Pfütze,n
 Wohnmobil
 der Wohnwagen
 das Zelt
 das Wetter
 unmöglich
 campen
 zelten
 
 die Sonne
 der Schnee 
 der Regen 
 die Wolke
 der Wind 
 der Nebel 
 das Gewitter 
 Der Donner
 der Blitz
 der Sturm.-stürmig
 der Grund,'e
 
 Südtirol
 zwei Grad
 nicht weit genug
 Hausdach
 Zum Glück haben wir noch am selben Tag
 selben Tag = gelichen Tag
 Glück X Pech
 brauchbaren
 farblos
 Traumwetter
 Schwarzwald
 
 Der Norden
 Der Westen
 Der Süden
 der Osten
 
 Niemals ohne seife waschen!!
 
 wolkenlos
 arbeitlos
 
 Wir hatten Lust auf Frühling.
 
 Wie ist das Wetter ? der Winter der Herbst Der Sommer Der Frühlig
 
 Es Regnet.---der Regen
 Es schneit.---das Schnee
 Es ist sonnig.--die Sonne
 Es ist windig.--der Wind
 Es ist bewölkt.--die Wolke
 Es ist neblig.--der Nebel
 Es donnert un blitzt..--das Gewitter
 
 
 Es ist warm Es sind 25 Grad.
 
 Es ist kalt.Es sind minus -2 Grad.
 
 Es ist kühl.Es sind plus + 8 Grad.

In Herbst ist es kalt. || Im Herbst ist es kühl.

                          Im Früglig regnet es.

Unser Ziel war Südtirol,denn dort ist es im März schon oft sehr warm.
Leider waren wir nur ein paar denn dann ist d Unwetter gekommen.
Es war perfekt,denn wir hatten ein Traumwetter.
Nächstes Jahr fahren wir lieber ans Mittelmeer,deen dort ist es auch im Herbst noch schön warm.


da ist es immer so windig.Ich möchte lieber im Cafê in der Sonne sitzen

Hier es regnet schon seit dre Tagen schon,seit drei Tagen.

Wir haben wunderschönes Frühlingswetter.Es ist warm und sonnig.

In den Bergen ist es kalt und es gibt viel schnee.

Heute Nachmittag gibt es Gewitter.

---

## 24

https://hueber.de/shared/uebungen/menschen/kb/a1/livebook/l24/index.php




Welches Datum war gestern/vorgestern/voreiner Wocher?
  
  Gestern / Vorsgestern / Vor einer Woche
  
Welches Datum ist heute /morgen /übermorgen / in einer Woche ?

  Heute /Morgen/Übermorgen/In einer
  
  Woche ist der ......
  
  Welche datum war Mittwoch for einer Woche
  
  Welche datum ist nächsten Freitag.
  
  Heute ist der siebste August.
  
  Heute ist der siebste Achte
  
  Ich fahre am achten August/Achten nach Berlin
  
  Ich fahre vom sechzehnten bis(zum) dreiundzwanzigsten August/Achten nach Berlin.
  
  Welcher Tag ist heute ? 
  
  -der achtundzwanzigste Februar.
  
  Ich würde gern mit der feiern.
  
  würden
  ıch  | würden
  du   | würdest
  er/sie/es | würde
  wir | würden
  ihr | würdet
  sie/Sie | würden
  
  Ich würde dich gern ins Kino einladen.
  
  Ich würde gern viel Geld haben.
  
  Wir würden das gern mit dir feiern.
  
  Ich würde gern Glüklich sein.
  
  Was würden Sie am liebsten jeden Tag machen ?
   +Ich würde gern jeden Morgen spät aufstehen
   
   Am liebsten würde ich jeden Tag schwimmen gehen.Ich würde gern um die Welt.
   
   Ich würde gern mit dir in einer Altbauwohnung wohnen.2 zimmer , Küche ,Bad und einem (und'nem) kleinen Balkon.
   
   Ich muss Benzin kaufen.
   
  Ich muss unbedingt Benzin kaufen. --nicht sofort.


  das Geschenk,e
  
  die Einweihungsparty,s
  
  die Tradition,en
  
  das Brot,e
  
  das Salz,e
  
  Weihnachten
  
  das Ostern
  
  die Prüfung,en
  
  bestanden
  
  die Einweihungsparty,s
  
  das Silvester
  
  der Karneval
  
  die Hochzeit,en
  
  das Neujahr
  
  der Geburstag,e
  
  das Geschenk,e

das Band
die Band
der Band

das Geschankband,''er                           
das Schere,n
schneiden
einpacken
das Geschenkpapier,e
das Examen,-                                             
die Examina                                              
feiern                               

1-6
1-sehr gut
2-gut
3-befriedigen
4-Gusreichend
5-mongelhaft
6-unganügend 











---

---

# B1

https://hueber.de/shared/uebungen/menschen/kb/b1/menu.php



















---

# B2- C1

https://www.hueber.de/shared/livebook/menschen-im-beruf/medizin/b2-c1/html5.html


https://www.hueber.de/lernen/deutsch-als-fremdsprache

---

# Deutsch im Krankenhaus Neu

https://www.klett-sprachen.de/deutsch-im-krankenhaus-neu/r-1/78#reiter=titel&niveau=A2-B2
















